#!/usr/bin/env python3
"""
bda_spec.py  -  Big Data and Data Science FTS v0.1: five state regions, each its own FTS over one managed element of
the Knowledge Area, derived from the DMBOK Big Data and Analytics context diagram (deck pages 79 to 82) and aligned to
the Global Data Asset Protocol.

Howard's managed elements (22 Sep 2026): 1 the Big Data Strategy and Standards of the scope (business needs, strategy,
standards); 2 a Big Data Platform (one per platform, with the build, buy or rent decision); 3 a Data Source (one per
source: chosen under the sourcing plan, acquired, ingested, aligned for analysis, retired); 4 an Analytical Model (one
per hypothesis or model: hypothesis and methods developed, explored, validated, deployed, monitored, enhanced, retired);
5 a Data Insight (one per finding: drafted, reviewed for trust and ethics, published, superseded or withdrawn).
Decisions 22 Sep 2026: BDA gates Global registration of an acquired source (chosen under a strategy in force),
materialisation (ingested and aligned on a platform in service), release of a model output or insight (deployed model,
insight published after the trust and ethics review, which is a hard gate: structural path plus a Non-waivable guard),
supersession by an enhanced model (event) and the assurance trigger on model drift, a source alert or a platform breach;
model validation is an assurance service; guards are Conditional so assets outside big data are unaffected; every
transition carries a Decision Right (holders drafted, REVIEW).

Usage: python bda_spec.py [out_dir] [--overrides spec/big_data_data_science_overrides.json]   -> big_data_data_science.fts.json
"""
import json, os, sys
from ka_build import build

SRC_DECK = "DMBOK Data Lifecycle and KA Context Diagrams.pdf, Big Data and Analytics pages 79 to 82 (What, Why, Activities, Role Players and Technical Drivers); Howard names the KA Big Data and Data Science"
SRC_HOWARD = "Howard Diesel, 22 Sep 2026: five BDA managed elements (Big Data Strategy and Standards; Big Data Platform; Data Source; Analytical Model; Data Insight), Global gating of acquisition, release, supersession and monitoring, the trust and ethics review as a hard gate on publication, BDA stepped in both Customer Master runs"
SRC_PROTOCOL = "global_protocol.fts.json v0.2.1 for the contribution targets; data_governance v0.2, data_quality, data_security, metadata_management, data_storage_operations, data_integration_interoperability, data_warehousing_bi, data_architecture and reference_master_data v0.1 for the couplings"

CONTEXT = {
    "knowledgeArea": "Big Data and Data Science",
    "definition": "The collection (Big data) and analysis (Data Science, Analytics and Visualization) of many different types of data to find answers and insights for questions that are not known at the start of the analysis. Generate, store and analyse larger amounts of data: Big Data (volume, variety and velocity it is produced); Data Scientists (people who mine and develop predictive, machine learning and prescriptive models and analytics); Data Science (applies data mining, statistical analysis and machine learning with data integration and data modelling to predict behaviours; forward looking, where BI describes past trends).",
    "ensures": "Data sources are chosen, acquired, ingested and aligned on a governed platform under a big data strategy and standards; hypotheses and models are developed, explored, validated, deployed and monitored; and the insights they produce are reviewed for trust and ethics before they are published, superseded or withdrawn.",
    "goals": ["Discover relationships between data and the business", "Support the iterative integration of data source(s) into the enterprise", "Discover and analyse new factors that might affect the business", "Publish data using visualization techniques in an appropriate, trusted and ethical manner"],
    "businessDrivers": ["The desire to discover and act on business opportunities through applying techniques on diversely generated data", "Data Science can improve operations", "Machine learning for automation of complex time-consuming activities"],
    "inputs": ["Business Strategy and Goals", "Build/Buy/Rent Decision Tree", "IT Standards", "Data Sources"],
    "processes": [
        {"id": "1", "name": "Define Big Data Strategy and Business Needs", "phase": "P", "subActivities": []},
        {"id": "2", "name": "Choose Data Sources", "phase": "P", "subActivities": []},
        {"id": "3", "name": "Acquire and Ingest Data Sources", "phase": "D", "subActivities": []},
        {"id": "4", "name": "Develop Hypotheses and Methods", "phase": "D", "subActivities": []},
        {"id": "5", "name": "Integrate/Align Data For Analysis", "phase": "D", "subActivities": []},
        {"id": "6", "name": "Explore Data Using Models", "phase": "D", "subActivities": []},
        {"id": "7", "name": "Deploy and Monitor", "phase": "O", "subActivities": []},
    ],
    "deliverables": ["Big Data Strategy and Standards", "Data Sourcing Plan", "Acquired Data Sources", "Initial data analysis and hypotheses", "Data insights and findings", "Enhancement Plan"],
    "suppliers": ["Big Data Platform Architects", "Data Scientists", "Data Producers", "Data Suppliers", "Information Consumers"],
    "participants": ["Big Data Platform Architects", "Ingestion Architects", "Data SMEs", "Data Scientists", "Analytic Design Lead", "DM Managers", "Metadata Specialists"],
    "consumers": ["Business Partners", "Business Executives", "IT Executives"],
    "techniques": ["Data Mashups", "Machine Learning Techniques", "Advanced Supervised Learning"],
    "tools": ["Distributed File-based Solutions", "Columnar Compression", "MPP Shared-Nothing Architectures", "In-memory Computing and Databases", "In-database Algorithms", "Data Visualization toolsets"],
    "metrics": ["Data usage metrics", "Response and performance metrics", "Data loading and scanning metrics", "Learnings and Stories"],
    "phaseTags": "(P) Planning, (C) Control, (D) Development, (O) Operations",
}

KA_SUBJECT = "Big Data and Data Science Knowledge Area: five managed elements, one FTS (state region) each; the Data Asset is the Global subject reached through contributions"
REGIONS = [
    ("REG-BDA-BDS", "Big Data Strategy and Standards", "BDS", "Whether the big data strategy and standards of the scope have the business needs defined, are defined, approved, in force or under review.", "STS-BDS-01", "Exactly one active state; a strategy under review keeps the standards in force.",
     "Big Data Strategy and Standards of the governed scope: the business needs and goals, the big data strategy, the standards (IT standards applied, ethics and trust standard for publication) and the data sourcing plan every platform, source, model and insight is governed by",
     {"instanceScope": "One instance per governed scope.", "elementKind": "Governing element (strategy and standards)", "contributesTo": "Existence: an acquired source is registered only under a strategy in force (TR-EX-01, with the source chosen); otherwise it gates the platforms, sources, models and insights through cross-region constraints.", "conditionsThatMatter": "None; business needs defined; strategy and standards defined; approved; in force; under review."}),
    ("REG-BDA-PLT", "Big Data Platform", "PLT", "Whether a big data platform has its build, buy or rent decision made, is provisioned, in service, under scaling or decommissioned.", "STS-PLT-01", "Exactly one active state per platform; In Service means loading, scanning, response and performance metrics are measured against target.",
     "Big Data Platform: one platform (distributed file-based, MPP shared-nothing, in-memory, columnar) decided by the build, buy or rent decision tree under the IT standards, provisioned, operated, scaled and decommissioned",
     {"instanceScope": "One instance per platform.", "elementKind": "Managed platform element", "contributesTo": "Existence: a source is materialised only when ingested and aligned on a platform in service (TR-EX-02); Assurance: a platform performance breach emits the assurance trigger (TR-AS-05).", "conditionsThatMatter": "None; decided; provisioned; in service; under scaling; decommissioned."}),
    ("REG-BDA-SRC", "Data Source", "SRC", "Whether one data source is chosen under the sourcing plan, acquired, ingested into the platform, aligned for analysis, under a source alert or retired.", "STS-SRC-01", "Exactly one active state per source; Aligned means the source is integrated and aligned for analysis with its metadata and lineage recorded.",
     "Data Source: one internal or external source (feed, stream, dataset, warehouse population, master data domain) chosen under the Data Sourcing Plan, acquired, ingested into a platform, integrated and aligned for analysis, and retired",
     {"instanceScope": "One instance per data source.", "elementKind": "Managed per-source element", "contributesTo": "Existence: an acquired source is registered only when chosen under the sourcing plan (TR-EX-01) and materialised only when ingested and aligned on a platform in service (TR-EX-02); Assurance: a source alert emits the assurance trigger (TR-AS-05).", "conditionsThatMatter": "None; chosen; acquired; ingested; aligned; source alert; retired."}),
    ("REG-BDA-MDL", "Analytical Model", "MDL", "Whether one hypothesis or analytical model is developed, explored, validated, deployed, under a drift alert, under enhancement or retired.", "STS-MDL-01", "Exactly one active state per model; a Deployed Model is monitored; a model under enhancement keeps the deployed version in use until the enhanced version is deployed.",
     "Analytical Model: one hypothesis with its methods, developed into a predictive, machine learning or prescriptive model, explored on aligned sources, validated, deployed, monitored, enhanced under the Enhancement Plan and retired",
     {"instanceScope": "One instance per hypothesis or model.", "elementKind": "Managed per-model element", "contributesTo": "Availability: a model output or insight is released only from a deployed model (TR-AV-01); Existence: an enhanced model deployed supersedes the previous model version (TR-EX-03); Assurance: a drift or performance alert emits the assurance trigger (TR-AS-05) and model validation supplies assurance evidence (TR-AS-02).", "conditionsThatMatter": "None; hypothesis developed; explored; validated; deployed; drift alert; under enhancement; retired."}),
    ("REG-BDA-INS", "Data Insight", "INS", "Whether one data insight or finding is drafted, reviewed for trust and ethics, published, superseded or withdrawn.", "STS-INS-01", "Exactly one active state per insight; Published is reached only from Reviewed (the trust and ethics review is a hard gate).",
     "Data Insight: one finding, learning or story produced by a model and published with visualization techniques in an appropriate, trusted and ethical manner to its consumers",
     {"instanceScope": "One instance per insight or finding.", "elementKind": "Managed per-insight element (deliverable)", "contributesTo": "Availability: a model output or insight is released only when the insight is published after the trust and ethics review (TR-AV-01, the review Non-waivable).", "conditionsThatMatter": "None; drafted; reviewed; published; superseded; withdrawn."}),
]
STATES = [
    ("STS-BDS-01", "REG-BDA-BDS", "No Big Data Strategy", True, False, "No big data strategy or standards exist for the scope; analytics are ad hoc.", "The absence of a strategy remains visible to governance bodies.", ["inputs:Business Strategy and Goals"]),
    ("STS-BDS-02", "REG-BDA-BDS", "Defined Business Needs", False, False, "The business needs, goals and the questions worth exploring are defined from the business strategy and goals.", "Each need remains traceable to the business strategy.", ["process:1", "inputs:Business Strategy and Goals"]),
    ("STS-BDS-03", "REG-BDA-BDS", "Defined Big Data Strategy and Standards", False, False, "The strategy, the standards (IT standards applied, trust and ethics standard for publication) and the data sourcing plan are drafted and await approval.", "The strategy remains consistent with the enterprise data architecture and the IT standards.", ["process:1", "deliverable:Big Data Strategy and Standards", "inputs:IT Standards"]),
    ("STS-BDS-04", "REG-BDA-BDS", "Approved Strategy and Standards", False, False, "The strategy, standards and sourcing plan are approved by the DM managers and business executives.", "The approved documents and approving authority remain traceable.", ["process:1", "deliverable:Data Sourcing Plan"]),
    ("STS-BDS-05", "REG-BDA-BDS", "Strategy and Standards in Force", False, False, "The strategy and standards are published and applied; every platform, source, model and insight is governed by them; data usage metrics are measured.", "Every managed element follows the standards in force; the sourcing plan remains current.", ["process:1", "metric:Data usage metrics"]),
    ("STS-BDS-06", "REG-BDA-BDS", "Strategy under Review", False, False, "The strategy or standards are under review after learnings, a business change or a standards change while the standards in force stay in force.", "The standards in force remain valid until the review is approved.", ["process:1", "metric:Learnings and Stories"]),
    ("STS-PLT-01", "REG-BDA-PLT", "No Platform", True, False, "No big data platform exists for the need.", "The unmet platform need remains visible.", ["inputs:Build/Buy/Rent Decision Tree"]),
    ("STS-PLT-02", "REG-BDA-PLT", "Decided Platform", False, False, "The build, buy or rent decision is made under the decision tree and the IT standards; the platform design is agreed.", "The decision, its options and its authority remain recorded.", ["process:1", "process:3", "inputs:Build/Buy/Rent Decision Tree", "inputs:IT Standards"]),
    ("STS-PLT-03", "REG-BDA-PLT", "Provisioned Platform", False, False, "The platform (distributed file, MPP, in-memory, columnar) is provisioned in an environment in service and its loading and scanning metrics baselined; acceptance is pending.", "Acceptance results remain recorded against the design.", ["process:3", "tools:Distributed File-based Solutions", "tools:MPP Shared-Nothing Architectures", "tools:In-memory Computing and Databases"]),
    ("STS-PLT-04", "REG-BDA-PLT", "Platform in Service", False, False, "The platform is accepted into service and monitored; response, performance, loading and scanning metrics are within target.", "Metrics remain within target; the support arrangement is in force.", ["process:7", "metric:Response and performance metrics", "metric:Data loading and scanning metrics"]),
    ("STS-PLT-05", "REG-BDA-PLT", "Platform under Scaling", False, False, "A capacity or performance breach is open; scaling runs while the platform stays in service; a Data Asset issue is logged.", "The breach, its owner and the DG issue reference remain explicit.", ["process:7", "metric:Response and performance metrics"]),
    ("STS-PLT-06", "REG-BDA-PLT", "Decommissioned Platform", False, False, "The platform is decommissioned after its sources are retired or migrated.", "The decommission record and the destination of migrated sources remain recorded.", ["process:7"]),
    ("STS-SRC-01", "REG-BDA-SRC", "No Data Source", True, False, "The source is not chosen for analysis.", "The candidate remains visible in the sourcing plan.", ["inputs:Data Sources"]),
    ("STS-SRC-02", "REG-BDA-SRC", "Chosen Data Source", False, False, "The source is chosen under the sourcing plan: value, cost, quality, privacy basis and licence assessed.", "The assessment remains traceable to the sourcing plan.", ["process:2", "deliverable:Data Sourcing Plan"]),
    ("STS-SRC-03", "REG-BDA-SRC", "Acquired Data Source", False, False, "The source is acquired: agreement or licence in place, delivery arranged, producer or supplier engaged.", "The acquisition agreement and delivery arrangement remain recorded.", ["process:3", "deliverable:Acquired Data Sources"]),
    ("STS-SRC-04", "REG-BDA-SRC", "Ingested Data Source", False, False, "The source is ingested into a platform in service; loading and scanning metrics are recorded; alignment is pending.", "The ingestion record (delivery, run, volumes) remains recorded.", ["process:3", "metric:Data loading and scanning metrics"]),
    ("STS-SRC-05", "REG-BDA-SRC", "Aligned Data Source", False, False, "The source is integrated and aligned for analysis: mapped, cleansed, keys aligned with data mashups, metadata and lineage recorded.", "Alignment and lineage remain current; the source is fit for exploration.", ["process:5", "techniques:Data Mashups"]),
    ("STS-SRC-06", "REG-BDA-SRC", "Source Alert", False, False, "A schema change, delivery failure or quality drift in the source is detected; a Data Asset issue is logged while the aligned data stays available.", "The alert, its cause and the DG issue reference remain explicit.", ["process:7"]),
    ("STS-SRC-07", "REG-BDA-SRC", "Retired Data Source", False, False, "The source is withdrawn from analysis; its agreement closed and its lineage retained.", "The retirement record remains retrievable.", ["process:7"]),
    ("STS-MDL-01", "REG-BDA-MDL", "No Model", True, False, "No hypothesis or model exists for the question.", "The open question remains visible.", ["process:4"]),
    ("STS-MDL-02", "REG-BDA-MDL", "Developed Hypothesis", False, False, "The hypothesis and its methods (data mining, statistical, machine learning) are developed from the business needs.", "The hypothesis remains traceable to a business need; methods are recorded.", ["process:4", "techniques:Machine Learning Techniques"]),
    ("STS-MDL-03", "REG-BDA-MDL", "Explored Model", False, False, "The model is explored on aligned sources; initial data analysis and findings are drafted.", "The exploration record (sources, methods, results) remains recorded.", ["process:6", "deliverable:Initial data analysis and hypotheses", "tools:In-database Algorithms"]),
    ("STS-MDL-04", "REG-BDA-MDL", "Validated Model", False, False, "The model is validated (holdout, review of methods, bias and fitness checks); it is fit for deployment.", "Validation results remain recorded against the hypothesis.", ["process:6", "techniques:Advanced Supervised Learning"]),
    ("STS-MDL-05", "REG-BDA-MDL", "Deployed Model", False, False, "The model is deployed on a platform in service and monitored for drift and performance.", "Monitoring is active; the deployed version and its validation remain recorded.", ["process:7"]),
    ("STS-MDL-06", "REG-BDA-MDL", "Model Drift Alert", False, False, "Monitoring flags drift or a performance breach; a Data Asset issue is logged; the model stays deployed while investigated.", "The alert, its owner and the DG issue reference remain explicit.", ["process:7"]),
    ("STS-MDL-07", "REG-BDA-MDL", "Model under Enhancement", False, False, "The enhancement plan is executed on a new version while the deployed version stays in use.", "The deployed version remains valid until the enhanced version is deployed.", ["process:7", "deliverable:Enhancement Plan"]),
    ("STS-MDL-08", "REG-BDA-MDL", "Retired Model", False, False, "The model is withdrawn from use; its hypothesis, validation and learnings are retained.", "The retirement record and learnings remain retrievable.", ["process:7", "metric:Learnings and Stories"]),
    ("STS-INS-01", "REG-BDA-INS", "No Insight", True, False, "No insight has been drafted from the model.", "The absence of a finding remains visible.", ["process:6"]),
    ("STS-INS-02", "REG-BDA-INS", "Drafted Insight", False, False, "The insight or finding is drafted from the model with its visualization; the trust and ethics review is pending.", "The draft remains traceable to the model and sources.", ["process:6", "deliverable:Data insights and findings", "tools:Data Visualization toolsets"]),
    ("STS-INS-03", "REG-BDA-INS", "Reviewed Insight", False, False, "The insight passed the trust and ethics review (appropriate, trusted, ethical, privacy respected); publication is authorised.", "The review record and its authority remain traceable.", ["process:7"]),
    ("STS-INS-04", "REG-BDA-INS", "Published Insight", False, False, "The insight is published using visualization techniques to its consumers; usage and learnings are measured.", "The published version, audience and usage remain recorded.", ["process:7", "metric:Data usage metrics", "metric:Learnings and Stories"]),
    ("STS-INS-05", "REG-BDA-INS", "Superseded Insight", False, False, "The insight is replaced by a newer finding; the earlier version is retained.", "The supersession record remains retrievable.", ["process:7"]),
    ("STS-INS-06", "REG-BDA-INS", "Withdrawn Insight", False, False, "The insight is withdrawn for a trust, ethics, accuracy or privacy reason and retained with the reason.", "The withdrawal reason and authority remain recorded.", ["process:7"]),
]
EVENTS = {
    "EV-BDS-01": ("Business needs definition", "Request"), "EV-BDS-02": ("Strategy definition", "Evidence trigger"), "EV-BDS-03": ("Strategy approval", "Decision outcome"), "EV-BDS-04": ("Strategy rejection", "Decision outcome"), "EV-BDS-05": ("Standards publication", "Decision outcome"), "EV-BDS-06": ("Strategy review trigger", "Monitoring trigger"), "EV-BDS-07": ("Reviewed strategy approval", "Decision outcome"), "EV-BDS-08": ("Strategy retirement", "Decision outcome"),
    "EV-PLT-01": ("Platform decision", "Decision outcome"), "EV-PLT-02": ("Provisioning completion", "Evidence trigger"), "EV-PLT-03": ("Platform acceptance", "Decision outcome"), "EV-PLT-04": ("Provisioning rejection", "Decision outcome"), "EV-PLT-05": ("Capacity breach", "Monitoring trigger"), "EV-PLT-06": ("Scaling completion", "Assessment outcome"), "EV-PLT-07": ("Platform decommission", "Decision outcome"),
    "EV-SRC-01": ("Source assessment", "Request"), "EV-SRC-02": ("Source acquisition", "Decision outcome"), "EV-SRC-03": ("Source rejection", "Decision outcome"), "EV-SRC-04": ("Ingestion completion", "Evidence trigger"), "EV-SRC-05": ("Alignment completion", "Evidence trigger"), "EV-SRC-06": ("Source alert", "Monitoring trigger"), "EV-SRC-07": ("Alert resolution", "Assessment outcome"), "EV-SRC-08": ("Source retirement", "Decision outcome"), "EV-SRC-09": ("New delivery", "Time trigger"),
    "EV-MDL-01": ("Hypothesis development", "Request"), "EV-MDL-02": ("Exploration completion", "Evidence trigger"), "EV-MDL-03": ("Validation success", "Assessment outcome"), "EV-MDL-04": ("Hypothesis revision", "Decision outcome"), "EV-MDL-05": ("Model deployment", "Decision outcome"), "EV-MDL-06": ("Drift alert", "Monitoring trigger"), "EV-MDL-07": ("Drift resolution", "Assessment outcome"), "EV-MDL-08": ("Enhancement request", "Request"), "EV-MDL-09": ("Enhanced model deployment", "Decision outcome"), "EV-MDL-10": ("Model retirement", "Decision outcome"),
    "EV-INS-01": ("Insight draft", "Evidence trigger"), "EV-INS-02": ("Trust and ethics review pass", "Decision outcome"), "EV-INS-03": ("Trust and ethics review failure", "Decision outcome"), "EV-INS-04": ("Insight publication", "Decision outcome"), "EV-INS-05": ("Insight supersession", "Decision outcome"), "EV-INS-06": ("Insight withdrawal", "Decision outcome"), "EV-INS-07": ("Insight redraft", "Request"),
}
DR = {
    "DR-BDA-01": ("Approve the Big Data Strategy and Standards", "ROLE-BDA-P06", "REVIEW: drafted holder"),
    "DR-BDA-02": ("Define, Review and Retire the Strategy and Standards", "ROLE-BDA-P06", "REVIEW: drafted holder"),
    "DR-BDA-03": ("Decide, Provision, Scale and Decommission a Platform", "ROLE-BDA-P01", "REVIEW: drafted holder"),
    "DR-BDA-04": ("Choose, Acquire and Retire a Data Source", "ROLE-BDA-P03", "REVIEW: drafted holder"),
    "DR-BDA-05": ("Ingest, Align and Refresh a Data Source", "ROLE-BDA-P02", "REVIEW: drafted holder"),
    "DR-BDA-06": ("Develop, Explore, Validate and Enhance a Model", "ROLE-BDA-P04", "REVIEW: drafted holder"),
    "DR-BDA-07": ("Deploy, Monitor and Retire a Model", "ROLE-BDA-P05", "REVIEW: drafted holder"),
    "DR-BDA-08": ("Review an Insight for Trust and Ethics", "ROLE-BDA-P06", "REVIEW: drafted holder"),
    "DR-BDA-09": ("Draft, Publish, Supersede and Withdraw an Insight", "ROLE-BDA-P05", "REVIEW: drafted holder"),
}
ROLES = [
    ("ROLE-BDA-S01", "Big Data Platform Architects", "Supplier", "Supply platform options and the build, buy or rent decision tree."), ("ROLE-BDA-S02", "Data Scientists", "Supplier", "Supply hypotheses and methods."), ("ROLE-BDA-S03", "Data Producers", "Supplier", "Supply internal data sources."), ("ROLE-BDA-S04", "Data Suppliers", "Supplier", "Supply external data sources."), ("ROLE-BDA-S05", "Information Consumers", "Supplier", "Supply questions and feedback."),
    ("ROLE-BDA-P01", "Big Data Platform Architects", "Participant", "Decide, provision, scale and decommission platforms."), ("ROLE-BDA-P02", "Ingestion Architects", "Participant", "Ingest and align sources."), ("ROLE-BDA-P03", "Data SMEs", "Participant", "Assess and choose sources; give business meaning."), ("ROLE-BDA-P04", "Data Scientists", "Participant", "Develop, explore, validate and enhance models."), ("ROLE-BDA-P05", "Analytic Design Lead", "Participant", "Deploy and monitor models; draft and publish insights."), ("ROLE-BDA-P06", "DM Managers", "Participant", "Approve the strategy and standards; review insights for trust and ethics."), ("ROLE-BDA-P07", "Metadata Specialists", "Participant", "Record alignment metadata and lineage."),
    ("ROLE-BDA-C01", "Business Partners", "Consumer", "Consume insights."), ("ROLE-BDA-C02", "Business Executives", "Consumer", "Consume insights and act on opportunities."), ("ROLE-BDA-C03", "IT Executives", "Consumer", "Consume platform and usage metrics."),
]
TRANS = [
    ("TR-BDS-01", "Define Business Needs", "STS-BDS-01", "STS-BDS-02", "EV-BDS-01", "The business strategy and goals are available and the needs and questions worth exploring are recorded.", "DR-BDA-02", ["SVC-BDA-01"], ["ACT-BDA-1"]),
    ("TR-BDS-02", "Define Strategy and Standards", "STS-BDS-02", "STS-BDS-03", "EV-BDS-02", "The strategy, standards and sourcing plan are drafted within the enterprise data architecture in force and the IT standards.", "DR-BDA-02", ["SVC-BDA-01"], ["ACT-BDA-1"]),
    ("TR-BDS-03", "Approve Strategy and Standards", "STS-BDS-03", "STS-BDS-04", "EV-BDS-03", "The DM managers and business executives approve the strategy, standards and sourcing plan.", "DR-BDA-01", ["SVC-BDA-01"], ["ACT-BDA-1"]),
    ("TR-BDS-04", "Return Strategy for Rework", "STS-BDS-03", "STS-BDS-02", "EV-BDS-04", "The strategy is rejected with recorded reasons.", "DR-BDA-01", ["SVC-BDA-01"], ["ACT-BDA-1"]),
    ("TR-BDS-05", "Bring Standards into Force", "STS-BDS-04", "STS-BDS-05", "EV-BDS-05", "The strategy and standards are published and the data usage metrics defined.", "DR-BDA-02", ["SVC-BDA-01"], ["ACT-BDA-1"]),
    ("TR-BDS-06", "Open Strategy Review", "STS-BDS-05", "STS-BDS-06", "EV-BDS-06", "Learnings, a business change or a standards change trigger a review; the standards in force are retained meanwhile.", "DR-BDA-02", ["SVC-BDA-01"], ["ACT-BDA-1"]),
    ("TR-BDS-07", "Approve Reviewed Strategy", "STS-BDS-06", "STS-BDS-05", "EV-BDS-07", "The reviewed strategy and standards are approved and published.", "DR-BDA-01", ["SVC-BDA-01"], ["ACT-BDA-1"]),
    ("TR-BDS-08", "Retire Strategy", "STS-BDS-06", "STS-BDS-01", "EV-BDS-08", "No platform is in service and the retirement is recorded.", "DR-BDA-02", ["SVC-BDA-01"], ["ACT-BDA-1"]),
    ("TR-PLT-01", "Decide Platform", "STS-PLT-01", "STS-PLT-02", "EV-PLT-01", "The build, buy or rent decision is made under the decision tree and the IT standards.", "DR-BDA-03", ["SVC-BDA-02"], ["ACT-BDA-1", "ACT-BDA-3"]),
    ("TR-PLT-02", "Provision Platform", "STS-PLT-02", "STS-PLT-03", "EV-PLT-02", "The platform is provisioned in an environment in service and its loading and scanning metrics baselined.", "DR-BDA-03", ["SVC-BDA-02"], ["ACT-BDA-3"]),
    ("TR-PLT-03", "Accept Platform into Service", "STS-PLT-03", "STS-PLT-04", "EV-PLT-03", "Acceptance passes and monitoring of response, performance, loading and scanning metrics is active.", "DR-BDA-03", ["SVC-BDA-02"], ["ACT-BDA-3", "ACT-BDA-7"]),
    ("TR-PLT-04", "Return Platform for Rework", "STS-PLT-03", "STS-PLT-02", "EV-PLT-04", "Acceptance fails with recorded reasons.", "DR-BDA-03", ["SVC-BDA-02"], ["ACT-BDA-3"]),
    ("TR-PLT-05", "Open Scaling", "STS-PLT-04", "STS-PLT-05", "EV-PLT-05", "A capacity or performance breach is detected; a Data Asset issue is logged and the assurance trigger emitted.", "DR-BDA-03", ["SVC-BDA-02"], ["ACT-BDA-7"]),
    ("TR-PLT-06", "Complete Scaling", "STS-PLT-05", "STS-PLT-04", "EV-PLT-06", "Scaling returns the platform within its targets.", "DR-BDA-03", ["SVC-BDA-02"], ["ACT-BDA-7"]),
    ("TR-PLT-07", "Decommission Platform", "STS-PLT-04", "STS-PLT-06", "EV-PLT-07", "All sources on the platform are retired or migrated and the decommission recorded.", "DR-BDA-03", ["SVC-BDA-02"], ["ACT-BDA-7"]),
    ("TR-PLT-08", "Decommission Platform under Scaling", "STS-PLT-05", "STS-PLT-06", "EV-PLT-07", "A platform that cannot be scaled to target is replaced; sources migrated or retired first.", "DR-BDA-03", ["SVC-BDA-02"], ["ACT-BDA-7"]),
    ("TR-PLT-09", "Re-provision Platform", "STS-PLT-06", "STS-PLT-02", "EV-PLT-01", "A decommissioned platform is needed again and its decision re-made.", "DR-BDA-03", ["SVC-BDA-02"], ["ACT-BDA-3"]),
    ("TR-SRC-01", "Choose Source", "STS-SRC-01", "STS-SRC-02", "EV-SRC-01", "The source is assessed under the sourcing plan for value, cost, quality, privacy basis and licence, and chosen.", "DR-BDA-04", ["SVC-BDA-03"], ["ACT-BDA-2"]),
    ("TR-SRC-02", "Acquire Source", "STS-SRC-02", "STS-SRC-03", "EV-SRC-02", "The agreement or licence is in place and delivery arranged with the producer or supplier.", "DR-BDA-04", ["SVC-BDA-03"], ["ACT-BDA-3"]),
    ("TR-SRC-03", "Reject Source", "STS-SRC-02", "STS-SRC-01", "EV-SRC-03", "The assessment fails or the acquisition is declined with recorded reasons.", "DR-BDA-04", ["SVC-BDA-03"], ["ACT-BDA-2"]),
    ("TR-SRC-04", "Ingest Source", "STS-SRC-03", "STS-SRC-04", "EV-SRC-04", "The source is ingested into a platform in service over an exchange in operation; loading and scanning metrics recorded.", "DR-BDA-05", ["SVC-BDA-04"], ["ACT-BDA-3"]),
    ("TR-SRC-05", "Align Source", "STS-SRC-04", "STS-SRC-05", "EV-SRC-05", "The source is integrated and aligned for analysis with its metadata and lineage recorded.", "DR-BDA-05", ["SVC-BDA-04"], ["ACT-BDA-5"]),
    ("TR-SRC-06", "Raise Source Alert", "STS-SRC-05", "STS-SRC-06", "EV-SRC-06", "A schema change, delivery failure or quality drift is detected; a Data Asset issue is logged and the assurance trigger emitted.", "DR-BDA-05", ["SVC-BDA-04"], ["ACT-BDA-7"]),
    ("TR-SRC-07", "Realign Source", "STS-SRC-06", "STS-SRC-05", "EV-SRC-07", "The cause is resolved and the source realigned.", "DR-BDA-05", ["SVC-BDA-04"], ["ACT-BDA-5"]),
    ("TR-SRC-08", "Retire Source", "STS-SRC-05", "STS-SRC-07", "EV-SRC-08", "No model depends on the source; its agreement is closed and lineage retained.", "DR-BDA-04", ["SVC-BDA-03"], ["ACT-BDA-7"]),
    ("TR-SRC-09", "Retire Source on Alert", "STS-SRC-06", "STS-SRC-07", "EV-SRC-08", "An unresolved alert leads to withdrawal of the source; no model depends on it.", "DR-BDA-04", ["SVC-BDA-03"], ["ACT-BDA-7"]),
    ("TR-SRC-10", "Re-choose Source", "STS-SRC-07", "STS-SRC-02", "EV-SRC-01", "A retired source is needed again and reassessed under the sourcing plan.", "DR-BDA-04", ["SVC-BDA-03"], ["ACT-BDA-2"]),
    ("TR-SRC-11", "Refresh Ingestion", "STS-SRC-05", "STS-SRC-04", "EV-SRC-09", "A new delivery is ingested; alignment is redone on the new data.", "DR-BDA-05", ["SVC-BDA-04"], ["ACT-BDA-3"]),
    ("TR-MDL-01", "Develop Hypothesis", "STS-MDL-01", "STS-MDL-02", "EV-MDL-01", "A hypothesis and its methods are developed from a defined business need.", "DR-BDA-06", ["SVC-BDA-05"], ["ACT-BDA-4"]),
    ("TR-MDL-02", "Explore Data", "STS-MDL-02", "STS-MDL-03", "EV-MDL-02", "The model is explored on aligned sources and the initial analysis recorded.", "DR-BDA-06", ["SVC-BDA-05"], ["ACT-BDA-6"]),
    ("TR-MDL-03", "Validate Model", "STS-MDL-03", "STS-MDL-04", "EV-MDL-03", "Holdout, method, bias and fitness checks pass on sources with conforming quality.", "DR-BDA-06", ["SVC-BDA-06"], ["ACT-BDA-6"]),
    ("TR-MDL-04", "Revise Hypothesis", "STS-MDL-03", "STS-MDL-02", "EV-MDL-04", "Exploration or validation does not support the hypothesis; it is revised.", "DR-BDA-06", ["SVC-BDA-05"], ["ACT-BDA-4"]),
    ("TR-MDL-05", "Deploy Model", "STS-MDL-04", "STS-MDL-05", "EV-MDL-05", "The validated model is deployed on a platform in service within the privacy basis of its sources and monitoring is active.", "DR-BDA-07", ["SVC-BDA-06"], ["ACT-BDA-7"]),
    ("TR-MDL-06", "Raise Drift Alert", "STS-MDL-05", "STS-MDL-06", "EV-MDL-06", "Monitoring flags drift or a performance breach; a Data Asset issue is logged and the assurance trigger emitted.", "DR-BDA-07", ["SVC-BDA-06"], ["ACT-BDA-7"]),
    ("TR-MDL-07", "Resolve Drift Alert", "STS-MDL-06", "STS-MDL-05", "EV-MDL-07", "The cause is resolved (retrained within tolerance) and the model verified.", "DR-BDA-07", ["SVC-BDA-06"], ["ACT-BDA-7"]),
    ("TR-MDL-08", "Open Enhancement", "STS-MDL-05", "STS-MDL-07", "EV-MDL-08", "An enhancement plan opens a new version; the deployed version stays in use.", "DR-BDA-06", ["SVC-BDA-05"], ["ACT-BDA-7"]),
    ("TR-MDL-09", "Open Enhancement on Alert", "STS-MDL-06", "STS-MDL-07", "EV-MDL-08", "A drift alert is answered by an enhancement; the deployed version stays in use.", "DR-BDA-06", ["SVC-BDA-05"], ["ACT-BDA-7"]),
    ("TR-MDL-10", "Deploy Enhanced Model", "STS-MDL-07", "STS-MDL-05", "EV-MDL-09", "The enhanced version is validated and deployed; it supersedes the previous version, whose insights are superseded or redrafted.", "DR-BDA-07", ["SVC-BDA-06"], ["ACT-BDA-7"]),
    ("TR-MDL-11", "Retire Model", "STS-MDL-05", "STS-MDL-08", "EV-MDL-10", "The model is withdrawn from use with its insights superseded or withdrawn; learnings retained.", "DR-BDA-07", ["SVC-BDA-06"], ["ACT-BDA-7"]),
    ("TR-MDL-12", "Retire Model on Alert", "STS-MDL-06", "STS-MDL-08", "EV-MDL-10", "An unresolved drift alert leads to withdrawal; insights superseded or withdrawn.", "DR-BDA-07", ["SVC-BDA-06"], ["ACT-BDA-7"]),
    ("TR-MDL-13", "Abandon Model", "STS-MDL-03", "STS-MDL-08", "EV-MDL-10", "An explored model is not pursued; the learnings are retained.", "DR-BDA-06", ["SVC-BDA-05"], ["ACT-BDA-6"]),
    ("TR-MDL-14", "Redevelop Model", "STS-MDL-08", "STS-MDL-02", "EV-MDL-01", "A retired model is needed again and its hypothesis redeveloped.", "DR-BDA-06", ["SVC-BDA-05"], ["ACT-BDA-4"]),
    ("TR-INS-01", "Draft Insight", "STS-INS-01", "STS-INS-02", "EV-INS-01", "A finding is drafted from an explored, validated or deployed model with its visualization.", "DR-BDA-09", ["SVC-BDA-08"], ["ACT-BDA-6"]),
    ("TR-INS-02", "Review Insight", "STS-INS-02", "STS-INS-03", "EV-INS-02", "The trust and ethics review passes: appropriate, trusted, ethical, privacy respected.", "DR-BDA-08", ["SVC-BDA-07"], ["ACT-BDA-7"]),
    ("TR-INS-03", "Reject Insight", "STS-INS-02", "STS-INS-06", "EV-INS-03", "The trust and ethics review fails; the draft is withdrawn with the reason recorded.", "DR-BDA-08", ["SVC-BDA-07"], ["ACT-BDA-7"]),
    ("TR-INS-04", "Publish Insight", "STS-INS-03", "STS-INS-04", "EV-INS-04", "The reviewed insight is published using visualization techniques under the standards in force.", "DR-BDA-09", ["SVC-BDA-08"], ["ACT-BDA-7"]),
    ("TR-INS-05", "Supersede Insight", "STS-INS-04", "STS-INS-05", "EV-INS-05", "A newer finding replaces the insight; the earlier version is retained.", "DR-BDA-09", ["SVC-BDA-08"], ["ACT-BDA-7"]),
    ("TR-INS-06", "Withdraw Insight", "STS-INS-04", "STS-INS-06", "EV-INS-06", "The insight is withdrawn for a trust, ethics, accuracy or privacy reason.", "DR-BDA-09", ["SVC-BDA-07"], ["ACT-BDA-7"]),
    ("TR-INS-07", "Redraft Superseded Insight", "STS-INS-05", "STS-INS-02", "EV-INS-07", "A superseded insight is redrafted from the current model.", "DR-BDA-09", ["SVC-BDA-08"], ["ACT-BDA-6"]),
    ("TR-INS-08", "Redraft Withdrawn Insight", "STS-INS-06", "STS-INS-02", "EV-INS-07", "A withdrawn insight is redrafted with the reason addressed.", "DR-BDA-09", ["SVC-BDA-08"], ["ACT-BDA-6"]),
]
SERVICES = [
    ("SVC-BDA-01", "Governance", "Big Data Strategy and Standards", "Business needs definition; strategy definition, approval, publication, review, retirement.", "Business needs; big data strategy and standards; data sourcing plan; data usage metrics."),
    ("SVC-BDA-02", "Control", "Platform Provisioning and Operation", "Platform decision; provisioning; acceptance; scaling; decommission.", "Build, buy or rent decision record; provisioned platform; loading, scanning, response and performance metrics."),
    ("SVC-BDA-03", "Governance", "Data Sourcing", "Source assessment; acquisition; rejection; retirement.", "Source assessment against the sourcing plan; acquisition agreement; retirement record."),
    ("SVC-BDA-04", "Control", "Ingestion and Alignment", "Ingestion; alignment; source alert; realignment; refresh.", "Ingestion record; aligned source with metadata and lineage; alert record."),
    ("SVC-BDA-05", "Control", "Hypothesis and Model Development", "Hypothesis development; exploration; revision; enhancement.", "Hypothesis and methods; initial data analysis; enhancement plan."),
    ("SVC-BDA-06", "Assurance", "Model Validation and Monitoring", "Validation; deployment; drift alert; resolution; retirement.", "Validation record (holdout, bias, fitness); deployment record; monitoring alerts."),
    ("SVC-BDA-07", "Assurance", "Insight Trust and Ethics Review", "Insight review; rejection; withdrawal.", "Trust and ethics review record; withdrawal reason."),
    ("SVC-BDA-08", "Governance", "Insight Publication", "Insight draft; publication; supersession; redraft.", "Published insight with visualization; learnings and stories; usage metrics."),
]
ACTS = [
    ("ACT-BDA-1", "Define Big Data Strategy and Business Needs", "1", "Transition-causing", ["REG-BDA-BDS", "REG-BDA-PLT"], ["TR-BDS-01", "TR-BDS-02", "TR-BDS-03", "TR-BDS-04", "TR-BDS-05", "TR-BDS-06", "TR-BDS-07", "TR-BDS-08", "TR-PLT-01"], ["SVC-BDA-01", "SVC-BDA-02"]),
    ("ACT-BDA-2", "Choose Data Sources", "2", "Transition-causing", ["REG-BDA-SRC"], ["TR-SRC-01", "TR-SRC-03", "TR-SRC-10"], ["SVC-BDA-03"]),
    ("ACT-BDA-3", "Acquire and Ingest Data Sources", "3", "Transition-causing", ["REG-BDA-SRC", "REG-BDA-PLT"], ["TR-SRC-02", "TR-SRC-04", "TR-SRC-11", "TR-PLT-01", "TR-PLT-02", "TR-PLT-03", "TR-PLT-04", "TR-PLT-09"], ["SVC-BDA-02", "SVC-BDA-03", "SVC-BDA-04"]),
    ("ACT-BDA-4", "Develop Hypotheses and Methods", "4", "Transition-causing", ["REG-BDA-MDL"], ["TR-MDL-01", "TR-MDL-04", "TR-MDL-14"], ["SVC-BDA-05"]),
    ("ACT-BDA-5", "Integrate/Align Data For Analysis", "5", "Transition-causing", ["REG-BDA-SRC"], ["TR-SRC-05", "TR-SRC-07"], ["SVC-BDA-04"]),
    ("ACT-BDA-6", "Explore Data Using Models", "6", "Transition-causing", ["REG-BDA-MDL", "REG-BDA-INS"], ["TR-MDL-02", "TR-MDL-03", "TR-MDL-13", "TR-INS-01", "TR-INS-07", "TR-INS-08"], ["SVC-BDA-05", "SVC-BDA-06", "SVC-BDA-08"]),
    ("ACT-BDA-7", "Deploy and Monitor", "7", "Transition-causing", ["REG-BDA-PLT", "REG-BDA-SRC", "REG-BDA-MDL", "REG-BDA-INS"], ["TR-PLT-03", "TR-PLT-05", "TR-PLT-06", "TR-PLT-07", "TR-PLT-08", "TR-SRC-06", "TR-SRC-08", "TR-SRC-09", "TR-MDL-05", "TR-MDL-06", "TR-MDL-07", "TR-MDL-08", "TR-MDL-09", "TR-MDL-10", "TR-MDL-11", "TR-MDL-12", "TR-INS-02", "TR-INS-03", "TR-INS-04", "TR-INS-05", "TR-INS-06"], ["SVC-BDA-02", "SVC-BDA-04", "SVC-BDA-06", "SVC-BDA-07", "SVC-BDA-08"]),
]
ARTEFACTS = [
    ("ART-BDA-01", "Big Data Strategy and Standards", "STS-BDS-04", "Define Big Data Strategy and Business Needs", "Evidences Approved Strategy and Standards."), ("ART-BDA-02", "Data Sourcing Plan", "STS-BDS-04", "Choose Data Sources", "Approved with the strategy; every source is chosen under it."), ("ART-BDA-03", "Build, Buy or Rent Decision Record", "STS-PLT-02", "Acquire and Ingest Data Sources", "Evidences Decided Platform."), ("ART-BDA-04", "Acquired Data Sources", "STS-SRC-03", "Acquire and Ingest Data Sources", "Evidences Acquired Data Source; cited by Global registration."), ("ART-BDA-05", "Initial data analysis and hypotheses", "STS-MDL-03", "Explore Data Using Models", "Evidences Explored Model."), ("ART-BDA-06", "Data insights and findings", "STS-INS-04", "Deploy and Monitor", "Evidences Published Insight; cited by Global release."), ("ART-BDA-07", "Enhancement Plan", "STS-MDL-07", "Deploy and Monitor", "Evidences Model under Enhancement; its deployment supersedes the previous version."),
]
CONTRIB = [
    ("CON-BDA-01", "TR-EX-01", "guard", {"BDS": ["STS-BDS-05", "STS-BDS-06"], "SRC": ["STS-SRC-02", "STS-SRC-03", "STS-SRC-04", "STS-SRC-05", "STS-SRC-06"]}, "An acquired data source is registered as a Data Asset only when chosen under the sourcing plan of a strategy in force.", "(BDA_strategy_in_force and BDA_source_chosen) or not BDA_source_active", "Conditional", "Applies when the asset being registered is an acquired source; assets outside big data are unaffected."),
    ("CON-BDA-02", "TR-EX-02", "guard", {"SRC": ["STS-SRC-05"], "PLT": ["STS-PLT-04", "STS-PLT-05"]}, "An acquired data source is materialised only when ingested and aligned for analysis on a platform in service.", "(BDA_source_aligned and BDA_platform_in_service) or not BDA_source_active", "Conditional", "Applies to the acquired source as a Data Asset."),
    ("CON-BDA-03", "TR-AV-01", "guard", {"MDL": ["STS-MDL-05", "STS-MDL-06", "STS-MDL-07"], "INS": ["STS-INS-04"]}, "Access to a model output or insight is released only from a deployed model with the insight published.", "(BDA_model_deployed and BDA_insight_published) or not BDA_insight_active", "Conditional", "Applies to the insight or model output as its own asset instance."),
    ("CON-BDA-04", "TR-AV-01", "guard", {"INS": ["STS-INS-03", "STS-INS-04"]}, "An insight is released only after the trust and ethics review has passed.", "BDA_insight_reviewed or not BDA_insight_active", "Non-waivable", "Howard, 22 Sep: the review is a hard gate; no exception bypasses it (the path to Published also runs only through Reviewed)."),
    ("CON-BDA-05", "TR-EX-03", "event", {"MDL": ["STS-MDL-07"]}, "An enhanced model deployed supersedes the previous model version.", "BDA_model_enhancing", "Conditional", "BDA emits EV-EX-03 when TR-MDL-10 deploys the enhanced version."),
    ("CON-BDA-06", "TR-AS-05", "event", {"MDL": ["STS-MDL-06"], "SRC": ["STS-SRC-06"], "PLT": ["STS-PLT-05"]}, "Model drift, a source alert or a platform breach is a material change affecting the assurance claim.", "BDA_model_drift or BDA_source_alert or BDA_platform_scaling", "Conditional", "BDA emits EV-AS-05 when TR-MDL-06, TR-SRC-06 or TR-PLT-05 fires."),
    ("CON-BDA-07", "TR-AS-02", "service", {"MDL": ["STS-MDL-04", "STS-MDL-05"]}, "Model Validation and Monitoring supplies assurance evidence for a model output or insight.", "SVC-BDA-06", "Conditional", "Assurance service; evidence EVD-BDA-08."),
]
KA_COUPLINGS = [
    ("KAC-BDA-01", "KA-DG", "TR-ISS-01", "EV-ISS-01", "BDA_model_drift", "Model drift, a source alert, a platform breach and a rejected or withdrawn insight are logged as Data Asset issues with source Big Data and Data Science (TR-MDL-06, TR-SRC-06, TR-PLT-05, TR-INS-03 and TR-INS-06 emit EV-ISS-01).", "DG owns escalation; BDA owns the remediation."),
    ("KAC-BDA-02", "KA-DII", "TR-EXC-07", "", "DII_exchange_operating", "A source is ingested over an exchange in operation (TR-SRC-04 and TR-SRC-11 cite the DII fact).", "Reverse coupling: a BDA transition cites a DII fact."),
    ("KAC-BDA-03", "KA-DS", "TR-PRV-02", "", "DS_privacy_basis_ok", "A source is chosen only with a lawful basis for the intended analysis and a model is deployed only within that basis (TR-SRC-01 and TR-MDL-05 cite the DS fact).", "Reverse coupling: a BDA transition cites a DS fact."),
    ("KAC-BDA-04", "KA-MM", "TR-AST-02", "", "BDA_source_aligned", "The alignment metadata and lineage of an aligned source are described in the metadata store (the MM transition cites the BDA fact).", "Forward coupling: an MM transition cites a BDA fact."),
    ("KAC-BDA-05", "KA-DQ", "TR-PDCA-03", "", "DQ_conforming", "A model is validated only on sources with conforming quality (TR-MDL-03 cites the DQ fact).", "Reverse coupling: a BDA transition cites a DQ fact."),
    ("KAC-BDA-06", "KA-DSO", "TR-ENV-03", "", "DSO_environment_in_service", "A platform is provisioned in an environment in service (TR-PLT-02 cites the DSO fact).", "Reverse coupling: a BDA transition cites a DSO fact."),
    ("KAC-BDA-07", "KA-DWBI", "TR-POP-03", "", "DWBI_population_reconciled", "A reconciled warehouse population may be an aligned source (TR-SRC-05 cites the DWBI fact where the source is the warehouse).", "Reverse coupling: a BDA transition cites a DWBI fact."),
    ("KAC-BDA-08", "KA-DA", "TR-EDA-05", "", "DA_architecture_in_force", "The strategy and standards are defined within the Enterprise Data Architecture in force (TR-BDS-02 cites the DA fact).", "Reverse coupling: a BDA transition cites a DA fact."),
    ("KAC-BDA-09", "KA-RMD", "TR-DOM-05", "", "RMD_domain_shared", "Master data is chosen as a source from a shared domain (TR-SRC-01 cites the RMD fact for master data sources).", "Reverse coupling: a BDA transition cites an RMD fact."),
]
FACT_BINDINGS = {
    "BDA_strategy_in_force": {"region": "REG-BDA-BDS", "states": ["STS-BDS-05", "STS-BDS-06"]},
    "BDA_platform_in_service": {"region": "REG-BDA-PLT", "states": ["STS-PLT-04", "STS-PLT-05"]},
    "BDA_platform_scaling": {"region": "REG-BDA-PLT", "states": ["STS-PLT-05"]},
    "BDA_source_active": {"region": "REG-BDA-SRC", "states": ["STS-SRC-02", "STS-SRC-03", "STS-SRC-04", "STS-SRC-05", "STS-SRC-06"]},
    "BDA_source_chosen": {"region": "REG-BDA-SRC", "states": ["STS-SRC-02", "STS-SRC-03", "STS-SRC-04", "STS-SRC-05", "STS-SRC-06"]},
    "BDA_source_ingested": {"region": "REG-BDA-SRC", "states": ["STS-SRC-04", "STS-SRC-05", "STS-SRC-06"]},
    "BDA_source_aligned": {"region": "REG-BDA-SRC", "states": ["STS-SRC-05"]},
    "BDA_source_alert": {"region": "REG-BDA-SRC", "states": ["STS-SRC-06"]},
    "BDA_model_active": {"region": "REG-BDA-MDL", "states": ["STS-MDL-02", "STS-MDL-03", "STS-MDL-04", "STS-MDL-05", "STS-MDL-06", "STS-MDL-07"]},
    "BDA_model_validated": {"region": "REG-BDA-MDL", "states": ["STS-MDL-04", "STS-MDL-05", "STS-MDL-06", "STS-MDL-07"]},
    "BDA_model_deployed": {"region": "REG-BDA-MDL", "states": ["STS-MDL-05", "STS-MDL-06", "STS-MDL-07"]},
    "BDA_model_drift": {"region": "REG-BDA-MDL", "states": ["STS-MDL-06"]},
    "BDA_model_enhancing": {"region": "REG-BDA-MDL", "states": ["STS-MDL-07"]},
    "BDA_insight_active": {"region": "REG-BDA-INS", "states": ["STS-INS-02", "STS-INS-03", "STS-INS-04"]},
    "BDA_insight_reviewed": {"region": "REG-BDA-INS", "states": ["STS-INS-03", "STS-INS-04"]},
    "BDA_insight_published": {"region": "REG-BDA-INS", "states": ["STS-INS-04"]},
    "BDA_insight_withdrawn": {"region": "REG-BDA-INS", "states": ["STS-INS-06"]},
}
XRG = [
    ("XRG-BDA-01", "A source is chosen only under a strategy and sourcing plan in force.", ["TR-SRC-01", "TR-SRC-10"], "Required", "BDS in ('STS-BDS-05','STS-BDS-06')"),
    ("XRG-BDA-02", "A source is ingested only into a platform in service.", ["TR-SRC-04", "TR-SRC-11"], "Required", "PLT in ('STS-PLT-04','STS-PLT-05')"),
    ("XRG-BDA-03", "A model is explored only on an aligned source.", ["TR-MDL-02"], "Required", "SRC in ('STS-SRC-05')"),
    ("XRG-BDA-04", "A model is deployed only on a platform in service.", ["TR-MDL-05", "TR-MDL-10"], "Required", "PLT in ('STS-PLT-04','STS-PLT-05')"),
    ("XRG-BDA-05", "An insight is drafted only from an explored, validated or deployed model.", ["TR-INS-01", "TR-INS-07", "TR-INS-08"], "Required", "MDL in ('STS-MDL-03','STS-MDL-04','STS-MDL-05','STS-MDL-06','STS-MDL-07')"),
    ("XRG-BDA-06", "An insight is published only under standards in force (the trust and ethics review is structural: Published is reached only from Reviewed).", ["TR-INS-04"], "Non-waivable", "BDS in ('STS-BDS-05','STS-BDS-06')"),
    ("XRG-BDA-07", "A platform is decommissioned only when no source is ingested on it.", ["TR-PLT-07", "TR-PLT-08"], "Required", "SRC in ('STS-SRC-01','STS-SRC-02','STS-SRC-03','STS-SRC-07')"),
    ("XRG-BDA-08", "A source is retired only when no model depends on it.", ["TR-SRC-08", "TR-SRC-09"], "Required", "MDL in ('STS-MDL-01','STS-MDL-08')"),
    ("XRG-BDA-09", "A model is retired only when its insights are superseded or withdrawn.", ["TR-MDL-11", "TR-MDL-12"], "Required", "INS in ('STS-INS-01','STS-INS-05','STS-INS-06')"),
    ("XRG-BDA-10", "The strategy is retired only when no platform is in service.", ["TR-BDS-08"], "Required", "PLT in ('STS-PLT-01','STS-PLT-06')"),
]
VECTORS = [
    ("CFG-BDA-01", "Greenfield", {"REG-BDA-BDS": "STS-BDS-01", "REG-BDA-PLT": "STS-PLT-01", "REG-BDA-SRC": "STS-SRC-01", "REG-BDA-MDL": "STS-MDL-01", "REG-BDA-INS": "STS-INS-01"}, "Initial configuration: no strategy, platform, source, model or insight; Global guards pass for assets outside big data."),
    ("CFG-BDA-02", "Strategy and platform in force", {"REG-BDA-BDS": "STS-BDS-05", "REG-BDA-PLT": "STS-PLT-04", "REG-BDA-SRC": "STS-SRC-01", "REG-BDA-MDL": "STS-MDL-01", "REG-BDA-INS": "STS-INS-01"}, "Legal: sources can be chosen and ingested; Global guards pass."),
    ("CFG-BDA-03", "Source aligned, hypothesis developed", {"REG-BDA-BDS": "STS-BDS-05", "REG-BDA-PLT": "STS-PLT-04", "REG-BDA-SRC": "STS-SRC-05", "REG-BDA-MDL": "STS-MDL-02", "REG-BDA-INS": "STS-INS-01"}, "Legal: the acquired source can be materialised; exploration can start."),
    ("CFG-BDA-04", "Model deployed, insight published", {"REG-BDA-BDS": "STS-BDS-05", "REG-BDA-PLT": "STS-PLT-04", "REG-BDA-SRC": "STS-SRC-05", "REG-BDA-MDL": "STS-MDL-05", "REG-BDA-INS": "STS-INS-04"}, "Legal: all BDA contributions satisfied; release passes; validation supplies assurance evidence."),
    ("CFG-BDA-05", "Insight drafted, not reviewed", {"REG-BDA-BDS": "STS-BDS-05", "REG-BDA-PLT": "STS-PLT-04", "REG-BDA-SRC": "STS-SRC-05", "REG-BDA-MDL": "STS-MDL-05", "REG-BDA-INS": "STS-INS-02"}, "Legal: release of the insight blocked by the Non-waivable review guard."),
    ("CFG-BDA-06", "Model drift alert", {"REG-BDA-BDS": "STS-BDS-05", "REG-BDA-PLT": "STS-PLT-04", "REG-BDA-SRC": "STS-SRC-05", "REG-BDA-MDL": "STS-MDL-06", "REG-BDA-INS": "STS-INS-04"}, "Legal: EV-AS-05 emitted; DG issue logged; the published insight stays available until withdrawn or superseded."),
    ("CFG-BDA-07", "Model under enhancement", {"REG-BDA-BDS": "STS-BDS-05", "REG-BDA-PLT": "STS-PLT-04", "REG-BDA-SRC": "STS-SRC-05", "REG-BDA-MDL": "STS-MDL-07", "REG-BDA-INS": "STS-INS-04"}, "Legal: EV-EX-03 emitted when the enhanced version is deployed; the deployed version stays in use."),
]
EVIDENCE = [
    ("EVD-BDA-01", "Strategy approval record", "Decision evidence", "TR-BDS-03", "Approved strategy, standards, sourcing plan; approving authority."), ("EVD-BDA-02", "Platform decision record", "Decision evidence", "TR-PLT-01", "Build, buy or rent decision, options considered, IT standards applied."), ("EVD-BDA-03", "Platform acceptance record", "Decision evidence", "TR-PLT-03", "Acceptance results; metric baselines; monitoring activation."), ("EVD-BDA-04", "Source assessment", "Governance evidence", "TR-SRC-01", "Value, cost, quality, privacy basis, licence; sourcing plan entry."), ("EVD-BDA-05", "Acquisition agreement", "Governance evidence", "TR-SRC-02", "Agreement or licence; delivery arrangement; supplier."), ("EVD-BDA-06", "Ingestion record", "Control evidence", "TR-SRC-04", "Delivery, run, volumes, loading and scanning metrics."), ("EVD-BDA-07", "Alignment record", "Control evidence", "TR-SRC-05", "Mappings, cleansing, key alignment, metadata and lineage entries."), ("EVD-BDA-08", "Validation record", "Assurance evidence", "TR-MDL-03", "Holdout results, method review, bias and fitness checks, source quality cited."), ("EVD-BDA-09", "Deployment record", "Decision evidence", "TR-MDL-05", "Deployed version, platform, privacy basis, monitoring thresholds."), ("EVD-BDA-10", "Drift alert record", "Control evidence", "TR-MDL-06", "Alert, cause, owner, DG issue reference, resolution or enhancement."), ("EVD-BDA-11", "Trust and ethics review record", "Assurance evidence", "TR-INS-02", "Review criteria (appropriate, trusted, ethical, privacy), outcome, reviewer."), ("EVD-BDA-12", "Publication record", "Governance evidence", "TR-INS-04", "Published version, visualization, audience, usage metric, learnings."),
]
EXC = [("EXC-BDA-01", "Pilot Model Deployment", "TR-MDL-05", "Deployment of a model validated on a partial holdout to a monitored pilot before full validation.", "DR-BDA-07", "Pilot scope and audience named, monitoring thresholds set, full validation scheduled with a date, privacy basis confirmed, DG informed, evidence retained; expires at the scheduled validation date. Never waives the trust and ethics review of an insight (CON-BDA-04 is Non-waivable).", "Draft / Approved / Expired / Closed")]

SPEC = {
    "meta": {"modelId": "KA-BDA", "name": "Big Data and Data Science FTS", "knowledgeArea": "Big Data and Data Science", "version": "0.1", "subjectType": KA_SUBJECT,
             "regionModel": "One FTS per managed element: the Big Data Strategy and Standards (scope level), a Big Data Platform (one per platform), a Data Source (one per source), an Analytical Model (one per hypothesis or model) and a Data Insight (one per finding) run concurrently and are coupled by cross-region constraints, facts and events, never a single subject.",
             "source": SRC_DECK + "; " + SRC_HOWARD + "; " + SRC_PROTOCOL,
             "note": "Five state regions, each its own FTS over one managed element of the Knowledge Area: the Big Data Strategy and Standards, a Big Data Platform, a Data Source, an Analytical Model and a Data Insight. The KA never becomes a region of the Data Asset; the source, the model and the insight reach the Global protocol through contributions (registration and materialisation of an acquired source, release of a model output or insight after the trust and ethics review, supersession by an enhanced model, the assurance trigger on drift, source alert or platform breach, and model validation as the assurance service), all Conditional except the Non-waivable review guard, so assets outside big data are unaffected, and couple to DG, DII, Data Security, Metadata, DQ, DSO, DWBI, Data Architecture and RMD.",
             "definition": CONTEXT["definition"], "factBindings": FACT_BINDINGS},
    "context": CONTEXT, "regions": REGIONS, "states": STATES, "transitions": TRANS, "events": EVENTS, "decisionRights": DR, "roles": ROLES, "artefacts": ARTEFACTS, "activities": ACTS, "services": SERVICES, "contributions": CONTRIB, "kaCouplings": KA_COUPLINGS, "crossRegionConstraints": XRG, "stateVectors": VECTORS, "evidence": EVIDENCE, "exceptions": EXC,
    "sources": [
        {"id": "SRC-BDA-001", "source": SRC_DECK, "type": "Primary (image pages, captured)", "location": "Chat upload; OneDrive Data Lifecycle folder", "use": "Definition, goals, drivers, inputs, processes, deliverables, role players, techniques, tools, metrics", "limitations": "The deck names the KA Big Data and Analytics; Howard names it Big Data and Data Science. The context diagram lists seven activities and six deliverables but no platform, source, model or insight lifecycle; the states are drafted from the activities, deliverables (Data Sourcing Plan, Acquired Data Sources, Initial data analysis and hypotheses, Data insights and findings, Enhancement Plan), the build, buy or rent input and the goal to publish in an appropriate, trusted and ethical manner. The Acquired Data Sources deliverable has no explicit acquisition lifecycle on the diagram."},
        {"id": "SRC-BDA-002", "source": SRC_HOWARD, "type": "Design direction", "location": "Chat", "use": "Managed elements (five, platform split out), Global gating, trust and ethics review as a hard gate", "limitations": ""},
        {"id": "SRC-BDA-003", "source": SRC_PROTOCOL, "type": "Alignment target", "location": "Private repo models/", "use": "Global transition IDs for contributions; KA transition IDs for couplings", "limitations": ""},
    ],
    "qaNotes": [
        {"severity": "note", "rule": "GA-005", "element": "KA-BDA", "finding": "The strategy and the platform change rarely relative to a source, model or insight and gate them through XRG-BDA-01..10; the Data Source, the Analytical Model and the Data Insight are per instance and are the BDA regions that gate Global registration, materialisation, release and supersession."},
        {"severity": "note", "rule": "capture", "element": "REG-BDA-MDL", "finding": "Source states (chosen, acquired, ingested, aligned, alert, retired), model states (hypothesis, explored, validated, deployed, drift alert, under enhancement, retired) and insight states (drafted, reviewed, published, superseded, withdrawn) are drafted from the activities and deliverables; the context diagram gives no lifecycle. For Howard's review."},
        {"severity": "note", "rule": "scope", "element": "CON-BDA-01", "finding": "All BDA contributions are Conditional and pass when the asset has no source, model or insight, except CON-BDA-04 (the trust and ethics review), which is Non-waivable but still passes when no insight exists for the asset. In the Customer Master runs the customer master is materialised before it is chosen as a source, so the acquisition guards pass on the absence of a source; they bite when the acquired source is itself the new asset (an external feed or stream)."},
        {"severity": "note", "rule": "derived", "element": "STATES", "finding": "All state names, events, decision rights, holders and services are first-pass drafts from the context diagram; every one is for Howard's review."},
    ],
}

if __name__ == "__main__":
    from ka_build import run_spec
    run_spec(SPEC, "big_data_data_science.fts.json")
