#!/usr/bin/env python3
"""
dcm_spec.py  -  Document and Content Management FTS v0.1: four state regions, each its own FTS over one managed
element of the Knowledge Area, derived from the DMBOK Document and Content Management context diagram (deck pages 64
to 68) and aligned to the Global Data Asset Protocol.

Howard's managed elements (22 Sep 2026): 1 the Content and Records Management Strategy of the scope with its content
handling policies and e-discovery approach; 2 the Information Architecture of the scope with the content repository,
taxonomy and metadata tagging; 3 a Record or Content Item of a Data Asset (one per item; declaration as a record is a
state of the one lifecycle); 4 a Legal Hold or e-discovery matter (one per matter).
Decisions 22 Sep 2026: DCM gates Global destruction (retention expired and no active hold), preservation (retention rule
assigned) and release of published content or a declared record; a hold raised emits the Assurance trigger and blocks
disposition; records retention and the audit trail is an assurance service; guards are Conditional so assets with no
content item are unaffected; every transition carries a Decision Right (holders confirmed 22 Sep 2026 from the shared role vocabulary, role_vocabulary.json).

Usage: python dcm_spec.py [out_dir] [--overrides spec/document_content_management_overrides.json]   -> document_content_management.fts.json
"""
import json, os, sys
from ka_build import build

SRC_DECK = "DMBOK Data Lifecycle and KA Context Diagrams.pdf, Document and Content Management pages 64 to 68 (What, Why, Activities, Role Players and Technical Drivers)"
SRC_HOWARD = "Howard Diesel, 22 Sep 2026: four DCM managed elements (Content and Records Management Strategy; Information Architecture and Content Repository; Record or Content Item of a Data Asset; Legal Hold or e-discovery matter), Global gating of destruction, preservation and release with the hold as the assurance trigger, one record lifecycle with declaration as a state"
SRC_PROTOCOL = "global_protocol.fts.json v0.2.1 for the contribution targets; data_governance v0.2, data_security, metadata_management, data_storage_operations, data_architecture and data_integration_interoperability v0.1 for the couplings"

CONTEXT = {
    "knowledgeArea": "Document and Content Management",
    "definition": "Planning, implementation, and control activities for lifecycle management of data and information found in any form or medium. Document and Content Management entails controlling the capture, storage, access and use of data and information stored outside relational databases.",
    "ensures": "Documents, records and content are captured, classified, published, retained, held, archived and disposed under a content and records strategy and handling policies, within an information architecture and repository, with an audit trail that answers regulatory, litigation and e-discovery obligations.",
    "goals": ["To comply with legal obligations and customer expectations regarding Records management", "To ensure effective and efficient storage, retrieval, and use of Documents and Content", "To ensure integration capabilities between structured and unstructured Content"],
    "businessDrivers": ["Regulatory compliance", "The ability to respond to litigation", "e-discovery", "Business continuity requirements", "Business efficiency", "Customer satisfaction"],
    "inputs": ["Business strategy", "IT strategy", "Legal retention requirements", "Text file", "Electronic format file", "Printed paper file", "Social media stream"],
    "processes": [
        {"id": "1", "name": "Plan for Lifecycle Management", "phase": "P", "subActivities": ["1.1 Plan for Records Management", "1.2 Develop a content strategy"]},
        {"id": "2", "name": "Create Content Handling Policies, including E-discovery approach", "phase": "P", "subActivities": [], "note": "No phase tag on the diagram; (P) inferred from its place between the planning and development activities."},
        {"id": "3", "name": "Define Information Architecture", "phase": "D", "subActivities": []},
        {"id": "4", "name": "Manage the Lifecycle", "phase": "O", "subActivities": ["4.1 Capture and Manage Records and Content (O)", "4.2 Retain, Dispose, and Archive Records and Content (O)"]},
        {"id": "5", "name": "Publish and Deliver Content", "phase": "O", "subActivities": []},
    ],
    "deliverables": ["Content and Records Management Strategy", "Policy and procedure", "Content Repository", "Managed record in many media formats", "Audit trail and log"],
    "suppliers": ["Legal team", "Business team", "IT team", "External party"],
    "participants": ["Data steward", "Data management professional", "Records management staff", "Content management staff", "Web development staff", "Librarians"],
    "consumers": ["Business user", "IT user", "Government regulatory agency", "Audit team", "External customer"],
    "techniques": ["Metadata tagging", "Data markup and exchange format", "Data mapping", "Storyboarding", "Infographics"],
    "tools": ["Office productivity software", "Enterprise content management system", "Controlled vocabulary / meta-data tool", "Knowledge management wiki", "Visual media tool", "Social media", "E-discovery technology"],
    "metrics": ["Compliance audit metric", "Return on investment", "Usage metric", "Record management KPI", "E-discovery KPI", "ECM program metric", "ECM operational metric"],
    "phaseTags": "(P) Planning, (C) Control, (D) Development, (O) Operations",
}

KA_SUBJECT = "Document and Content Management Knowledge Area: four managed elements, one FTS (state region) each; the Data Asset is the Global subject reached through contributions"
REGIONS = [
    ("REG-DCM-CRS", "Content and Records Management Strategy", "CRS", "Whether the content and records management strategy of the scope, with its handling policies and e-discovery approach, is planned, defined, approved, in force or under review.", "STS-CRS-01", "Exactly one active state; a strategy under review keeps the policies in force.",
     "Content and Records Management Strategy of the governed scope: the records management plan, the content strategy, the content handling policies (including the e-discovery approach) and the retention schedule every record and content item is managed under",
     {"instanceScope": "One instance per governed scope.", "elementKind": "Governing element (strategy and policy)", "contributesTo": "No Global transition is gated on the strategy directly; it gates capture, declaration and retention extension through cross-region constraints.", "conditionsThatMatter": "None; records management planned; content strategy defined; approved; in force; under review."}),
    ("REG-DCM-IAR", "Information Architecture and Content Repository", "IAR", "Whether the information architecture of the scope (taxonomy, controlled vocabulary, metadata tagging scheme, markup and exchange formats, repository design) is defined, approved, in force with the repository in service, or under change.", "STS-IAR-01", "Exactly one active state; an architecture under change keeps the repository in service.",
     "Information Architecture of the governed scope with its Content Repository: the taxonomy, controlled vocabulary, metadata tagging scheme, data markup and exchange formats and the enterprise content management repository content is captured into and delivered from",
     {"instanceScope": "One instance per governed scope.", "elementKind": "Governing element (architecture and platform)", "contributesTo": "No Global transition is gated on the architecture directly; it gates capture through a cross-region constraint (content is captured only into a repository in service).", "conditionsThatMatter": "None; defined; approved; in force; under change."}),
    ("REG-DCM-REC", "Record or Content Item of a Data Asset", "REC", "Whether one document, record or content item of a Data Asset is captured, classified, published, declared a record, archived, past its retention or disposed.", "STS-REC-01", "Exactly one active state per item; a Declared Record is locked against change and its retention period runs; Disposed Item is terminal per instance (a new version is a new item).",
     "Record or Content Item of a Data Asset: one document, record or content item in any form or medium (text, electronic, paper, social media) captured into the repository, classified and tagged, published and delivered, declared a record under the retention schedule, archived, and disposed with an audit trail",
     {"instanceScope": "One instance per record or content item.", "elementKind": "Managed per-item element", "contributesTo": "Existence: a document or content asset is destroyed only when the record's retention has expired and no hold is active (TR-EX-05, TR-EX-06); Custody: it enters preservation only with a retention rule assigned (TR-CP-02); Availability: access is released only to published content or a declared record under active management (TR-AV-01); Assurance: records retention and the audit trail supply assurance evidence (TR-AS-02).", "conditionsThatMatter": "None; captured; classified; published; declared record; archived; retention expired; disposed."}),
    ("REG-DCM-HLD", "Legal Hold or e-Discovery Matter", "HLD", "Whether a litigation, regulatory or investigation matter has a hold identified, active with its preservation notice issued, in discovery, or released.", "STS-HLD-01", "Exactly one active state per matter; while a hold is active or in discovery, no item in its scope is disposed.",
     "Legal Hold or e-Discovery Matter: one litigation, regulatory, contractual or investigation matter for which a preservation notice suspends disposition of the records in its scope and e-discovery collection, review and production may run",
     {"instanceScope": "One instance per matter.", "elementKind": "Managed per-matter element", "contributesTo": "Existence: an active hold blocks destruction (TR-EX-05, TR-EX-06; the DCM hold state stands behind the Global hold_active fact); Assurance: a hold raised is a material change affecting the assurance claim (TR-AS-05).", "conditionsThatMatter": "None; identified; active; in discovery; released."}),
]
STATES = [
    ("STS-CRS-01", "REG-DCM-CRS", "No Content and Records Strategy", True, False, "No content and records management strategy exists; documents and content are handled ad hoc.", "The absence of a strategy remains visible to governance bodies.", ["inputs:Business strategy", "inputs:Legal retention requirements"]),
    ("STS-CRS-02", "REG-DCM-CRS", "Planned Records Management", False, False, "The records management plan is drafted from the legal retention requirements: record classes, retention schedule, e-discovery obligations.", "Each retention rule remains traceable to its legal or business requirement.", ["process:1", "inputs:Legal retention requirements"]),
    ("STS-CRS-03", "REG-DCM-CRS", "Defined Content Strategy", False, False, "The content strategy and the content handling policies, including the e-discovery approach, are drafted and await approval.", "The strategy remains consistent with the business and IT strategies.", ["process:1", "process:2", "deliverable:Content and Records Management Strategy"]),
    ("STS-CRS-04", "REG-DCM-CRS", "Approved Strategy and Policies", False, False, "The strategy, the handling policies and the retention schedule are approved by the legal and business teams.", "The approved documents and approving authority remain traceable.", ["process:2", "deliverable:Policy and procedure"]),
    ("STS-CRS-05", "REG-DCM-CRS", "Strategy and Policies in Force", False, False, "The policies and procedures are published and applied; the retention schedule is in force; the compliance audit metric and record management KPI are measured.", "Every managed item follows the policies in force; the retention schedule remains current.", ["process:2", "metric:Compliance audit metric", "metric:Record management KPI", "metric:ECM program metric"]),
    ("STS-CRS-06", "REG-DCM-CRS", "Strategy under Review", False, False, "The strategy or policies are under review after an audit finding, a legal change or a strategy trigger while the policies in force stay in force.", "The policies in force remain valid until the review is approved.", ["process:2", "metric:Compliance audit metric"]),
    ("STS-IAR-01", "REG-DCM-IAR", "No Information Architecture", True, False, "No information architecture or content repository exists for the scope.", "The absence of a repository remains visible.", ["inputs:IT strategy"]),
    ("STS-IAR-02", "REG-DCM-IAR", "Defined Information Architecture", False, False, "The taxonomy, controlled vocabulary, metadata tagging scheme, markup and exchange formats and the repository design are defined and await approval.", "The definition remains consistent with the enterprise data architecture in force.", ["process:3", "techniques:Metadata tagging", "techniques:Data markup and exchange format", "tools:Controlled vocabulary / meta-data tool"]),
    ("STS-IAR-03", "REG-DCM-IAR", "Approved Information Architecture", False, False, "The information architecture is approved; the repository is being implemented.", "The approved architecture and approving authority remain traceable.", ["process:3"]),
    ("STS-IAR-04", "REG-DCM-IAR", "Information Architecture in Force", False, False, "The content repository is in service, the taxonomy in use and tagging enforced on capture; ECM operational metrics are measured.", "Every captured item carries the tags the architecture requires; the repository remains in service.", ["process:3", "deliverable:Content Repository", "tools:Enterprise content management system", "metric:ECM operational metric"]),
    ("STS-IAR-05", "REG-DCM-IAR", "Information Architecture under Change", False, False, "A taxonomy change or repository migration is under way while the architecture in force and the repository stay in service.", "The architecture in force remains valid until the change is approved; no item is lost in migration.", ["process:3"]),
    ("STS-REC-01", "REG-DCM-REC", "No Content Item", True, False, "No document, record or content item exists for the asset in the repository.", "The absence of the item remains visible.", ["inputs:Text file", "inputs:Electronic format file", "inputs:Printed paper file", "inputs:Social media stream"]),
    ("STS-REC-02", "REG-DCM-REC", "Captured Content", False, False, "The item is captured into the repository in its medium with its capture metadata; classification is pending.", "The capture record (source, medium, capturer, time) remains recorded.", ["process:4", "techniques:Metadata tagging"]),
    ("STS-REC-03", "REG-DCM-REC", "Classified Content", False, False, "The item is classified under the taxonomy and the handling policy: record class and retention category assigned, security classification and access level applied, tags complete.", "The classification, retention category and access level remain current and traceable to the policy.", ["process:4", "techniques:Metadata tagging", "tools:Controlled vocabulary / meta-data tool"]),
    ("STS-REC-04", "REG-DCM-REC", "Published Content", False, False, "The item is published and delivered to its consumers through the repository or a delivery channel under the handling policy; usage is measured.", "The published version, its audience and channel remain recorded; usage remains measured.", ["process:5", "metric:Usage metric", "tools:Knowledge management wiki", "tools:Social media"]),
    ("STS-REC-05", "REG-DCM-REC", "Declared Record", False, False, "The item is declared a record under the retention schedule: locked against change, its retention period running, its audit trail kept; it stays retrievable to its entitled consumers.", "The record remains unaltered; retention and audit trail remain current.", ["process:4", "deliverable:Managed record in many media formats", "deliverable:Audit trail and log"]),
    ("STS-REC-06", "REG-DCM-REC", "Archived Record", False, False, "The record is moved to archive storage under preservation controls; retention continues to run; retrieval is on request.", "Integrity and retrievability of the archived record remain evidenced.", ["process:4", "deliverable:Audit trail and log"]),
    ("STS-REC-07", "REG-DCM-REC", "Retention Expired", False, False, "The retention period has ended; disposition is due and awaits the disposition decision and the hold check.", "The expiry date, the disposition rule and any hold in scope remain explicit.", ["process:4", "metric:Record management KPI"]),
    ("STS-REC-08", "REG-DCM-REC", "Disposed Item", False, True, "The item is destroyed or transferred to an archive authority under the disposition rule; the audit trail and disposition certificate are retained.", "The disposition certificate and audit log remain retrievable; no content remains.", ["process:4", "deliverable:Audit trail and log"]),
    ("STS-HLD-01", "REG-DCM-HLD", "No Hold", True, False, "No litigation, regulatory or investigation matter places a hold on the records.", "The absence of a hold remains visible to the disposition check.", ["process:2"]),
    ("STS-HLD-02", "REG-DCM-HLD", "Identified Hold", False, False, "A matter is identified by the legal team; its scope (record classes, custodians, period) is being defined under the e-discovery approach.", "The matter, its trigger and its scope remain recorded.", ["process:2", "tools:E-discovery technology"]),
    ("STS-HLD-03", "REG-DCM-HLD", "Active Hold", False, False, "The preservation notice is issued and acknowledged by the custodians; disposition of every item in scope is suspended.", "No item in scope is disposed; acknowledgements remain recorded; the e-discovery KPI is measured.", ["process:4", "metric:E-discovery KPI"]),
    ("STS-HLD-04", "REG-DCM-HLD", "Hold in Discovery", False, False, "Collection, review and production of the records in scope are in progress; the hold stays active.", "The collection set, review status and productions remain recorded; no item in scope is disposed.", ["process:4", "tools:E-discovery technology", "metric:E-discovery KPI"]),
    ("STS-HLD-05", "REG-DCM-HLD", "Released Hold", False, False, "The legal team releases the hold; disposition of the items in scope resumes under the retention schedule; the hold record is retained.", "The release decision and its authority remain recorded.", ["process:4", "deliverable:Audit trail and log"]),
]
EVENTS = {
    "EV-CRS-01": ("Records management planning", "Request"), "EV-CRS-02": ("Content strategy definition", "Evidence trigger"), "EV-CRS-03": ("Strategy and policy approval", "Decision outcome"), "EV-CRS-04": ("Strategy rejection", "Decision outcome"), "EV-CRS-05": ("Policy publication", "Decision outcome"), "EV-CRS-06": ("Strategy review trigger", "Monitoring trigger"), "EV-CRS-07": ("Reviewed strategy approval", "Decision outcome"), "EV-CRS-08": ("Strategy retirement", "Decision outcome"),
    "EV-IAR-01": ("Architecture definition", "Request"), "EV-IAR-02": ("Architecture approval", "Decision outcome"), "EV-IAR-03": ("Definition rejection", "Decision outcome"), "EV-IAR-04": ("Repository in service", "Evidence trigger"), "EV-IAR-05": ("Architecture change trigger", "Monitoring trigger"), "EV-IAR-06": ("Architecture change approval", "Decision outcome"), "EV-IAR-07": ("Architecture retirement", "Decision outcome"),
    "EV-REC-01": ("Content capture", "Request"), "EV-REC-02": ("Content classification", "Evidence trigger"), "EV-REC-03": ("Content publication", "Decision outcome"), "EV-REC-04": ("Content withdrawal", "Decision outcome"), "EV-REC-05": ("Record declaration", "Decision outcome"), "EV-REC-06": ("Record archiving", "Time trigger"), "EV-REC-07": ("Archived record retrieval", "Request"), "EV-REC-08": ("Retention expiry", "Time trigger"), "EV-REC-09": ("Disposition authorisation", "Decision outcome"), "EV-REC-10": ("Retention extension", "Decision outcome"),
    "EV-HLD-01": ("Hold identification", "Request"), "EV-HLD-02": ("Preservation notice", "Decision outcome"), "EV-HLD-03": ("Hold withdrawal", "Decision outcome"), "EV-HLD-04": ("Discovery request", "Request"), "EV-HLD-05": ("Discovery completion", "Evidence trigger"), "EV-HLD-06": ("Hold release", "Decision outcome"), "EV-HLD-07": ("Hold record closure", "Decision outcome"),
}
DR = {
    "DR-DCM-01": ("Approve the Content and Records Strategy and Handling Policies", "ROLE-PM-DCM", "Confirmed 22 Sep 2026 (holder register): Document and Content Management Practice Manager; drafted as Data management professional"),
    "DR-DCM-02": ("Plan, Develop, Review and Retire the Strategy and Policies", "ROLE-RIM", "Confirmed 22 Sep 2026 (holder register): Records and Information Manager; drafted as Records management staff"),
    "DR-DCM-03": ("Approve the Information Architecture and its Changes", "ROLE-PM-DCM", "Confirmed 22 Sep 2026 (holder register): Document and Content Management Practice Manager; drafted as Data management professional"),
    "DR-DCM-04": ("Define, Change and Retire the Information Architecture and Repository", "ROLE-RIM", "Confirmed 22 Sep 2026 (holder register): Records and Information Manager; drafted as Content management staff"),
    "DR-DCM-05": ("Capture, Classify, Publish and Withdraw Content", "ROLE-RIM", "Confirmed 22 Sep 2026 (holder register): Records and Information Manager; drafted as Content management staff"),
    "DR-DCM-06": ("Declare, Archive, Retrieve and Extend a Record", "ROLE-RIM", "Confirmed 22 Sep 2026 (holder register): Records and Information Manager; drafted as Records management staff"),
    "DR-DCM-07": ("Dispose of a Record or Discard Content", "ROLE-RIM", "Confirmed 22 Sep 2026 (holder register): Records and Information Manager; drafted as Records management staff"),
    "DR-DCM-08": ("Identify, Issue, Release and Close a Legal Hold", "ROLE-LEGAL", "Confirmed 22 Sep 2026 (holder register): Legal Counsel; drafted as Legal team"),
}
ROLES = [
    ("ROLE-DCM-S01", "Legal team", "Supplier", "Supplies legal retention requirements, holds and the e-discovery obligations."), ("ROLE-DCM-S02", "Business team", "Supplier", "Supplies the business strategy and content needs."), ("ROLE-DCM-S03", "IT team", "Supplier", "Supplies the IT strategy and platforms."), ("ROLE-DCM-S04", "External party", "Supplier", "Supplies content and documents from outside the organisation."),
    ("ROLE-DCM-P01", "Data steward", "Participant", "Owns classification and retention decisions for the content in a domain."), ("ROLE-DCM-P02", "Data management professional", "Participant", "Approves the strategy, policies and information architecture."), ("ROLE-DCM-P03", "Records management staff", "Participant", "Plan records management; declare, archive, extend and dispose of records; administer holds."), ("ROLE-DCM-P04", "Content management staff", "Participant", "Define the information architecture; capture, classify, publish and withdraw content."), ("ROLE-DCM-P05", "Web development staff", "Participant", "Deliver published content through channels."), ("ROLE-DCM-P06", "Librarians", "Participant", "Maintain the taxonomy and controlled vocabulary."),
    ("ROLE-DCM-C01", "Business user", "Consumer", "Uses published content and records."), ("ROLE-DCM-C02", "IT user", "Consumer", "Uses content through systems."), ("ROLE-DCM-C03", "Government regulatory agency", "Consumer", "Receives records on regulatory request."), ("ROLE-DCM-C04", "Audit team", "Consumer", "Audits compliance and the audit trail."), ("ROLE-DCM-C05", "External customer", "Consumer", "Receives delivered content and their own records."),
]
TRANS = [
    ("TR-CRS-01", "Plan Records Management", "STS-CRS-01", "STS-CRS-02", "EV-CRS-01", "The legal retention requirements and the business and IT strategies are available; record classes, the retention schedule and e-discovery obligations are drafted.", "DR-DCM-02", ["SVC-DCM-01"], ["ACT-DCM-1"]),
    ("TR-CRS-02", "Develop Content Strategy", "STS-CRS-02", "STS-CRS-03", "EV-CRS-02", "The content strategy and the handling policies, including the e-discovery approach, are drafted from the records management plan.", "DR-DCM-02", ["SVC-DCM-01", "SVC-DCM-02"], ["ACT-DCM-1", "ACT-DCM-2"]),
    ("TR-CRS-03", "Approve Strategy and Policies", "STS-CRS-03", "STS-CRS-04", "EV-CRS-03", "The legal and business teams approve the strategy, policies and retention schedule.", "DR-DCM-01", ["SVC-DCM-02"], ["ACT-DCM-2"]),
    ("TR-CRS-04", "Return Strategy for Rework", "STS-CRS-03", "STS-CRS-02", "EV-CRS-04", "The strategy or policies are rejected with recorded reasons.", "DR-DCM-01", ["SVC-DCM-02"], ["ACT-DCM-2"]),
    ("TR-CRS-05", "Bring Policies into Force", "STS-CRS-04", "STS-CRS-05", "EV-CRS-05", "The policies and procedures are published and the retention schedule brought into force; the compliance audit metric is defined.", "DR-DCM-02", ["SVC-DCM-02"], ["ACT-DCM-2"]),
    ("TR-CRS-06", "Open Strategy Review", "STS-CRS-05", "STS-CRS-06", "EV-CRS-06", "An audit finding, a legal change or a strategy trigger is recorded; a Data Asset issue is logged for an audit finding; the policies in force are retained meanwhile.", "DR-DCM-02", ["SVC-DCM-02"], ["ACT-DCM-2"]),
    ("TR-CRS-07", "Approve Reviewed Strategy", "STS-CRS-06", "STS-CRS-05", "EV-CRS-07", "The reviewed strategy and policies are approved and published.", "DR-DCM-01", ["SVC-DCM-02"], ["ACT-DCM-2"]),
    ("TR-CRS-08", "Retire Strategy", "STS-CRS-06", "STS-CRS-01", "EV-CRS-08", "No item is under management and the retirement is recorded.", "DR-DCM-02", ["SVC-DCM-01"], ["ACT-DCM-2"]),
    ("TR-IAR-01", "Define Information Architecture", "STS-IAR-01", "STS-IAR-02", "EV-IAR-01", "The taxonomy, controlled vocabulary, tagging scheme, markup and exchange formats and repository design are defined within the enterprise data architecture in force.", "DR-DCM-04", ["SVC-DCM-03"], ["ACT-DCM-3"]),
    ("TR-IAR-02", "Approve Information Architecture", "STS-IAR-02", "STS-IAR-03", "EV-IAR-02", "The information architecture is approved.", "DR-DCM-03", ["SVC-DCM-03"], ["ACT-DCM-3"]),
    ("TR-IAR-03", "Withdraw Definition", "STS-IAR-02", "STS-IAR-01", "EV-IAR-03", "The definition is rejected with recorded reasons and withdrawn; a new definition follows.", "DR-DCM-03", ["SVC-DCM-03"], ["ACT-DCM-3"]),
    ("TR-IAR-04", "Bring Repository into Service", "STS-IAR-03", "STS-IAR-04", "EV-IAR-04", "The content repository is implemented in an environment in service, the taxonomy loaded and tagging enforced on capture.", "DR-DCM-04", ["SVC-DCM-03"], ["ACT-DCM-3"]),
    ("TR-IAR-05", "Open Architecture Change", "STS-IAR-04", "STS-IAR-05", "EV-IAR-05", "A taxonomy change or repository migration is recorded; the architecture in force and the repository stay in service.", "DR-DCM-04", ["SVC-DCM-03"], ["ACT-DCM-3"]),
    ("TR-IAR-06", "Approve Architecture Change", "STS-IAR-05", "STS-IAR-04", "EV-IAR-06", "The changed architecture is approved and every item re-tagged or migrated without loss.", "DR-DCM-03", ["SVC-DCM-03"], ["ACT-DCM-3"]),
    ("TR-IAR-07", "Retire Information Architecture", "STS-IAR-05", "STS-IAR-01", "EV-IAR-07", "No item is held in the repository and the decommission is recorded.", "DR-DCM-04", ["SVC-DCM-03"], ["ACT-DCM-3"]),
    ("TR-REC-01", "Capture Content", "STS-REC-01", "STS-REC-02", "EV-REC-01", "The item is captured into the repository in service in its medium with its capture metadata, under the policies in force.", "DR-DCM-05", ["SVC-DCM-04"], ["ACT-DCM-4"]),
    ("TR-REC-02", "Classify Content", "STS-REC-02", "STS-REC-03", "EV-REC-02", "The record class, retention category, security classification and access level are assigned and the tags completed under the taxonomy and the handling policy.", "DR-DCM-05", ["SVC-DCM-04"], ["ACT-DCM-4"]),
    ("TR-REC-03", "Publish Content", "STS-REC-03", "STS-REC-04", "EV-REC-03", "The item is published and delivered to its audience through the repository or a delivery channel under the handling policy and its access level.", "DR-DCM-05", ["SVC-DCM-05"], ["ACT-DCM-5"]),
    ("TR-REC-04", "Withdraw Content", "STS-REC-04", "STS-REC-03", "EV-REC-04", "The published item is withdrawn from its audience; the classified item remains.", "DR-DCM-05", ["SVC-DCM-05"], ["ACT-DCM-5"]),
    ("TR-REC-05", "Declare Record", "STS-REC-03", "STS-REC-05", "EV-REC-05", "The classified item is declared a record under the retention schedule in force; it is locked against change and its retention period starts.", "DR-DCM-06", ["SVC-DCM-06"], ["ACT-DCM-4"]),
    ("TR-REC-06", "Declare Published Record", "STS-REC-04", "STS-REC-05", "EV-REC-05", "The published item is declared a record; it stays retrievable to its audience but is locked against change.", "DR-DCM-06", ["SVC-DCM-06"], ["ACT-DCM-4"]),
    ("TR-REC-07", "Archive Record", "STS-REC-05", "STS-REC-06", "EV-REC-06", "The record moves to archive storage under preservation controls with its integrity evidenced; retention continues.", "DR-DCM-06", ["SVC-DCM-06"], ["ACT-DCM-4"]),
    ("TR-REC-08", "Retrieve Archived Record", "STS-REC-06", "STS-REC-05", "EV-REC-07", "An entitled request restores the record to active management.", "DR-DCM-06", ["SVC-DCM-06"], ["ACT-DCM-4"]),
    ("TR-REC-09", "Expire Retention", "STS-REC-05", "STS-REC-07", "EV-REC-08", "The retention period of the declared record ends; disposition becomes due.", "DR-DCM-06", ["SVC-DCM-06"], ["ACT-DCM-4"]),
    ("TR-REC-10", "Expire Archived Retention", "STS-REC-06", "STS-REC-07", "EV-REC-08", "The retention period of the archived record ends; disposition becomes due.", "DR-DCM-06", ["SVC-DCM-06"], ["ACT-DCM-4"]),
    ("TR-REC-11", "Dispose of Record", "STS-REC-07", "STS-REC-08", "EV-REC-09", "No hold is active over the record, disposition is authorised under the disposition rule, and the disposition certificate and audit log are retained.", "DR-DCM-07", ["SVC-DCM-07"], ["ACT-DCM-4"]),
    ("TR-REC-12", "Extend Retention", "STS-REC-07", "STS-REC-05", "EV-REC-10", "A new legal, regulatory or business obligation extends the retention period under the policies in force.", "DR-DCM-06", ["SVC-DCM-06"], ["ACT-DCM-4"]),
    ("TR-REC-13", "Discard Content", "STS-REC-03", "STS-REC-08", "EV-REC-09", "Classified content that is not declared a record is discarded under the handling policy; no hold is active over it; the audit log is retained.", "DR-DCM-07", ["SVC-DCM-07"], ["ACT-DCM-4"]),
    ("TR-HLD-01", "Identify Hold", "STS-HLD-01", "STS-HLD-02", "EV-HLD-01", "The legal team identifies a litigation, regulatory, contractual or investigation matter and defines its scope under the e-discovery approach.", "DR-DCM-08", ["SVC-DCM-08"], ["ACT-DCM-4"]),
    ("TR-HLD-02", "Issue Preservation Notice", "STS-HLD-02", "STS-HLD-03", "EV-HLD-02", "The preservation notice is issued to the custodians and acknowledged; disposition of every item in scope is suspended; the assurance trigger is emitted.", "DR-DCM-08", ["SVC-DCM-08"], ["ACT-DCM-4"]),
    ("TR-HLD-03", "Withdraw Identified Hold", "STS-HLD-02", "STS-HLD-01", "EV-HLD-03", "The legal team determines that no hold is required and records the reason.", "DR-DCM-08", ["SVC-DCM-08"], ["ACT-DCM-4"]),
    ("TR-HLD-04", "Start Discovery", "STS-HLD-03", "STS-HLD-04", "EV-HLD-04", "A collection, review or production request is received; the hold stays active.", "DR-DCM-08", ["SVC-DCM-08"], ["ACT-DCM-4"]),
    ("TR-HLD-05", "Complete Discovery", "STS-HLD-04", "STS-HLD-03", "EV-HLD-05", "The production is delivered and the collection set recorded; the hold stays active.", "DR-DCM-08", ["SVC-DCM-08"], ["ACT-DCM-4"]),
    ("TR-HLD-06", "Release Hold", "STS-HLD-03", "STS-HLD-05", "EV-HLD-06", "The matter is concluded and the legal team releases the hold; disposition resumes under the retention schedule.", "DR-DCM-08", ["SVC-DCM-08"], ["ACT-DCM-4"]),
    ("TR-HLD-07", "Release Hold after Discovery", "STS-HLD-04", "STS-HLD-05", "EV-HLD-06", "The matter concludes during discovery and the legal team releases the hold with the production record retained.", "DR-DCM-08", ["SVC-DCM-08"], ["ACT-DCM-4"]),
    ("TR-HLD-08", "Close Hold Record", "STS-HLD-05", "STS-HLD-01", "EV-HLD-07", "The hold record is closed and retained; the matter no longer constrains disposition.", "DR-DCM-08", ["SVC-DCM-08"], ["ACT-DCM-4"]),
    ("TR-HLD-09", "Reinstate Hold", "STS-HLD-05", "STS-HLD-03", "EV-HLD-02", "The matter is reopened and the preservation notice reissued.", "DR-DCM-08", ["SVC-DCM-08"], ["ACT-DCM-4"]),
]
SERVICES = [
    ("SVC-DCM-01", "Governance", "Records Management Planning and Content Strategy", "Records management planning; content strategy definition; strategy retirement.", "Records management plan; retention schedule; content strategy."),
    ("SVC-DCM-02", "Governance", "Content Handling Policy and e-Discovery Approach", "Policy approval, publication, review, rejection.", "Policies and procedures in force; e-discovery approach; compliance audit metric."),
    ("SVC-DCM-03", "Control", "Information Architecture and Repository", "Architecture definition, approval, repository in service, change, retirement.", "Taxonomy; controlled vocabulary; tagging scheme; content repository in service."),
    ("SVC-DCM-04", "Control", "Content Capture and Classification", "Content capture; classification.", "Captured item with capture metadata; classified and tagged item with retention category and access level."),
    ("SVC-DCM-05", "Control", "Content Publication and Delivery", "Publication; withdrawal.", "Published content delivered to its audience; usage metric."),
    ("SVC-DCM-06", "Assurance", "Records Retention and Audit Trail", "Record declaration; archiving; retrieval; retention expiry; extension.", "Declared record; audit trail and log; retention status; record management KPI."),
    ("SVC-DCM-07", "Control", "Disposition", "Disposition authorisation; discard.", "Disposition certificate; audit log."),
    ("SVC-DCM-08", "Assurance", "Legal Hold and e-Discovery", "Hold identification; preservation notice; discovery; release; closure.", "Preservation notice and acknowledgements; collection and production record; hold release; e-discovery KPI."),
]
ACTS = [
    ("ACT-DCM-1", "Plan for Lifecycle Management", "1", "Transition-causing", ["REG-DCM-CRS"], ["TR-CRS-01", "TR-CRS-02"], ["SVC-DCM-01"]),
    ("ACT-DCM-2", "Create Content Handling Policies, including E-discovery approach", "2", "Transition-causing", ["REG-DCM-CRS"], ["TR-CRS-02", "TR-CRS-03", "TR-CRS-04", "TR-CRS-05", "TR-CRS-06", "TR-CRS-07", "TR-CRS-08"], ["SVC-DCM-01", "SVC-DCM-02"]),
    ("ACT-DCM-3", "Define Information Architecture", "3", "Transition-causing", ["REG-DCM-IAR"], ["TR-IAR-01", "TR-IAR-02", "TR-IAR-03", "TR-IAR-04", "TR-IAR-05", "TR-IAR-06", "TR-IAR-07"], ["SVC-DCM-03"]),
    ("ACT-DCM-4", "Manage the Lifecycle", "4", "Transition-causing", ["REG-DCM-REC", "REG-DCM-HLD"], ["TR-REC-01", "TR-REC-02", "TR-REC-05", "TR-REC-06", "TR-REC-07", "TR-REC-08", "TR-REC-09", "TR-REC-10", "TR-REC-11", "TR-REC-12", "TR-REC-13", "TR-HLD-01", "TR-HLD-02", "TR-HLD-03", "TR-HLD-04", "TR-HLD-05", "TR-HLD-06", "TR-HLD-07", "TR-HLD-08", "TR-HLD-09"], ["SVC-DCM-04", "SVC-DCM-06", "SVC-DCM-07", "SVC-DCM-08"]),
    ("ACT-DCM-5", "Publish and Deliver Content", "5", "Transition-causing", ["REG-DCM-REC"], ["TR-REC-03", "TR-REC-04"], ["SVC-DCM-05"]),
]
ARTEFACTS = [
    ("ART-DCM-01", "Content and Records Management Strategy", "STS-CRS-04", "Plan for Lifecycle Management", "Evidences Approved Strategy and Policies."), ("ART-DCM-02", "Policy and procedure", "STS-CRS-05", "Create Content Handling Policies, including E-discovery approach", "Evidences Strategy and Policies in Force; governs every item."), ("ART-DCM-03", "Retention Schedule", "STS-CRS-02", "Plan for Lifecycle Management", "Drafted from the legal retention requirements; in force with the policies; cited by record declaration and retention expiry."), ("ART-DCM-04", "Content Repository", "STS-IAR-04", "Define Information Architecture", "Evidences Information Architecture in Force."), ("ART-DCM-05", "Managed record in many media formats", "STS-REC-05", "Manage the Lifecycle", "Evidences Declared Record; cited by Global release and preservation."), ("ART-DCM-06", "Audit trail and log", "STS-REC-08", "Manage the Lifecycle", "Evidences every lifecycle step and the disposition; cited by Global destruction and the assurance service."), ("ART-DCM-07", "Preservation Notice", "STS-HLD-03", "Manage the Lifecycle", "Evidences Active Hold; cited by the Global hold check."),
]
CONTRIB = [
    ("CON-DCM-01", "TR-EX-05", "guard", {"REC": ["STS-REC-07"], "HLD": ["STS-HLD-01", "STS-HLD-02", "STS-HLD-05"]}, "A document or content asset is destroyed only when its record's retention has expired and no hold is active over it.", "(DCM_retention_expired and not DCM_hold_active) or not DCM_record_active", "Conditional", "Applies when the asset has a record or content item; the DCM hold state stands behind the Global hold_active fact (XRG-001)."),
    ("CON-DCM-02", "TR-EX-06", "guard", {"REC": ["STS-REC-07"], "HLD": ["STS-HLD-01", "STS-HLD-02", "STS-HLD-05"]}, "A superseded document or content asset is destroyed only when its record's retention has expired and no hold is active over it.", "(DCM_retention_expired and not DCM_hold_active) or not DCM_record_active", "Conditional", "As CON-DCM-01 for the superseded asset."),
    ("CON-DCM-03", "TR-CP-02", "guard", {"REC": ["STS-REC-03", "STS-REC-04", "STS-REC-05", "STS-REC-06", "STS-REC-07"]}, "A document or content asset enters preservation custody only with a retention category assigned under the retention schedule.", "DCM_retention_assigned or not DCM_record_active", "Conditional", "The retention basis of the Global preservation criteria comes from the classification."),
    ("CON-DCM-04", "TR-AV-01", "guard", {"REC": ["STS-REC-04", "STS-REC-05"]}, "Access to a document or content asset is released only to content published through the repository under the handling policy or to a declared record under active management.", "DCM_content_released or not DCM_record_active", "Conditional", "Archived, expired and disposed items are not released; assets with no content item are unaffected."),
    ("CON-DCM-05", "TR-AS-05", "event", {"HLD": ["STS-HLD-03"]}, "A hold raised over the asset's records is a material change affecting the assurance claim: disposition is suspended and e-discovery obligations apply.", "DCM_hold_active", "Conditional", "DCM emits EV-AS-05 when TR-HLD-02 or TR-HLD-09 fires."),
    ("CON-DCM-06", "TR-AS-02", "service", {"REC": ["STS-REC-05", "STS-REC-06"]}, "Records Retention and Audit Trail supplies assurance evidence for the asset's records (declaration, retention status, audit log, compliance audit metric).", "SVC-DCM-06", "Conditional", "Assurance service; evidence EVD-DCM-06."),
    ("CON-DCM-07", "TR-AV-01", "event", {"REC": ["STS-REC-04", "STS-REC-05"]}, "Content published through the repository, or a record declared under active management, is the request to release access to it.", "DCM_record_active and DCM_content_released", "Conditional", "Howard, 23 Sep 2026: eleven Knowledge Areas gated TR-AV-01 and none raised it. Each Knowledge Area that owns an asset kind now raises the release request for the assets of its kind. Document and Content Management owns the record or content item; DCM emits EV-AV-01 when TR-REC-04 or TR-REC-05 fires."),
]
KA_COUPLINGS = [
    ("KAC-DCM-01", "KA-DG", "TR-ISS-01", "EV-ISS-01", "DCM_strategy_in_force", "A handling policy breach, a failed compliance audit or a missed hold is logged as a Data Asset issue with source Document and Content Management (TR-CRS-06 emits EV-ISS-01 on an audit finding).", "DG owns escalation; DCM owns the remediation."),
    ("KAC-DCM-02", "KA-DS", "TR-CLS-02", "", "DS_classified", "Content is classified with the Data Security classification and access level of its asset (TR-REC-02 cites the DS fact).", "Reverse coupling: a DCM transition cites a DS fact."),
    ("KAC-DCM-03", "KA-MM", "TR-AST-02", "", "DCM_content_classified", "The tags of classified content are described in the metadata store as the asset's metadata (the MM transition cites the DCM fact).", "Forward coupling: an MM transition cites a DCM fact."),
    ("KAC-DCM-04", "KA-DSO", "TR-STO-04", "", "DSO_instance_archived", "An archived record is held in an archived stored instance under preservation controls (TR-REC-07 cites the DSO fact).", "Reverse coupling: a DCM transition cites a DSO fact."),
    ("KAC-DCM-05", "KA-DA", "TR-EDA-05", "", "DA_architecture_in_force", "The information architecture is defined within the Enterprise Data Architecture in force (TR-IAR-01 cites the DA fact).", "Reverse coupling: a DCM transition cites a DA fact."),
    ("KAC-DCM-06", "KA-DII", "TR-DSV-04", "", "DII_service_published", "Content delivered by service is published through a published data service (TR-REC-03 cites the DII fact where delivery is by service).", "Reverse coupling: a DCM transition cites a DII fact."),
    ("KAC-DCM-07", "KA-DS", "TR-PRV-08", "", "DCM_item_disposed", "Personal data in a disposed record is evidenced removed by the disposition certificate (the DS transition cites the DCM fact).", "Forward coupling: a DS transition cites a DCM fact."),
]
FACT_BINDINGS = {
    "DCM_strategy_in_force": {"region": "REG-DCM-CRS", "states": ["STS-CRS-05", "STS-CRS-06"]},
    "DCM_policies_approved": {"region": "REG-DCM-CRS", "states": ["STS-CRS-04", "STS-CRS-05", "STS-CRS-06"]},
    "DCM_architecture_in_force": {"region": "REG-DCM-IAR", "states": ["STS-IAR-04", "STS-IAR-05"]},
    "DCM_record_active": {"region": "REG-DCM-REC", "states": ["STS-REC-02", "STS-REC-03", "STS-REC-04", "STS-REC-05", "STS-REC-06", "STS-REC-07"]},
    "DCM_content_classified": {"region": "REG-DCM-REC", "states": ["STS-REC-03", "STS-REC-04", "STS-REC-05", "STS-REC-06", "STS-REC-07"]},
    "DCM_retention_assigned": {"region": "REG-DCM-REC", "states": ["STS-REC-03", "STS-REC-04", "STS-REC-05", "STS-REC-06", "STS-REC-07"]},
    "DCM_content_released": {"region": "REG-DCM-REC", "states": ["STS-REC-04", "STS-REC-05"]},
    "DCM_record_declared": {"region": "REG-DCM-REC", "states": ["STS-REC-05", "STS-REC-06", "STS-REC-07"]},
    "DCM_record_archived": {"region": "REG-DCM-REC", "states": ["STS-REC-06"]},
    "DCM_retention_expired": {"region": "REG-DCM-REC", "states": ["STS-REC-07"]},
    "DCM_item_disposed": {"region": "REG-DCM-REC", "states": ["STS-REC-08"]},
    "DCM_hold_active": {"region": "REG-DCM-HLD", "states": ["STS-HLD-03", "STS-HLD-04"]},
    "DCM_hold_released": {"region": "REG-DCM-HLD", "states": ["STS-HLD-05"]},
}
XRG = [
    ("XRG-DCM-01", "Content is captured and classified only under policies in force.", ["TR-REC-01", "TR-REC-02"], "Required", "CRS in ('STS-CRS-05','STS-CRS-06')"),
    ("XRG-DCM-02", "Content is captured only into a repository in service under the information architecture.", ["TR-REC-01"], "Required", "IAR in ('STS-IAR-04','STS-IAR-05')"),
    ("XRG-DCM-03", "A record is disposed of, or content discarded, only when no legal hold is active or in discovery (legal hold check).", ["TR-REC-11", "TR-REC-13"], "Required", "HLD in ('STS-HLD-01','STS-HLD-02','STS-HLD-05')"),
    ("XRG-DCM-04", "A record is declared only under a retention schedule in force.", ["TR-REC-05", "TR-REC-06"], "Required", "CRS in ('STS-CRS-05','STS-CRS-06')"),
    ("XRG-DCM-05", "Retention is extended only under policies in force.", ["TR-REC-12"], "Required", "CRS in ('STS-CRS-05','STS-CRS-06')"),
    ("XRG-DCM-06", "The strategy is retired only when no item is under management.", ["TR-CRS-08"], "Required", "REC in ('STS-REC-01','STS-REC-08')"),
    ("XRG-DCM-07", "The information architecture is retired only when no item is held in the repository.", ["TR-IAR-07"], "Required", "REC in ('STS-REC-01','STS-REC-08')"),
]
VECTORS = [
    ("CFG-DCM-01", "Greenfield", {"REG-DCM-CRS": "STS-CRS-01", "REG-DCM-IAR": "STS-IAR-01", "REG-DCM-REC": "STS-REC-01", "REG-DCM-HLD": "STS-HLD-01"}, "Initial configuration: no strategy, repository, item or hold; Global guards pass for assets without a content item."),
    ("CFG-DCM-02", "Policies and repository in force, no item", {"REG-DCM-CRS": "STS-CRS-05", "REG-DCM-IAR": "STS-IAR-04", "REG-DCM-REC": "STS-REC-01", "REG-DCM-HLD": "STS-HLD-01"}, "Legal: content can be captured; Global guards pass."),
    ("CFG-DCM-03", "Declared record, no hold", {"REG-DCM-CRS": "STS-CRS-05", "REG-DCM-IAR": "STS-IAR-04", "REG-DCM-REC": "STS-REC-05", "REG-DCM-HLD": "STS-HLD-01"}, "Legal: release and preservation pass; destruction blocked until retention expires; retention supplies assurance evidence."),
    ("CFG-DCM-04", "Declared record under active hold", {"REG-DCM-CRS": "STS-CRS-05", "REG-DCM-IAR": "STS-IAR-04", "REG-DCM-REC": "STS-REC-05", "REG-DCM-HLD": "STS-HLD-03"}, "Legal: EV-AS-05 emitted; disposition and Global destruction blocked while the hold is active."),
    ("CFG-DCM-05", "Retention expired, no hold", {"REG-DCM-CRS": "STS-CRS-05", "REG-DCM-IAR": "STS-IAR-04", "REG-DCM-REC": "STS-REC-07", "REG-DCM-HLD": "STS-HLD-01"}, "Legal: disposition due; Global destruction passes the DCM guard; release blocked."),
    ("CFG-DCM-06", "Retention expired under hold", {"REG-DCM-CRS": "STS-CRS-05", "REG-DCM-IAR": "STS-IAR-04", "REG-DCM-REC": "STS-REC-07", "REG-DCM-HLD": "STS-HLD-04"}, "Legal: disposition and Global destruction blocked until the hold is released."),
]
EVIDENCE = [
    ("EVD-DCM-01", "Strategy and policy approval record", "Decision evidence", "TR-CRS-03", "Approved strategy, policies, retention schedule; approving authority."), ("EVD-DCM-02", "Information architecture approval record", "Decision evidence", "TR-IAR-02", "Approved taxonomy, vocabulary, tagging scheme, repository design."), ("EVD-DCM-03", "Capture record", "Control evidence", "TR-REC-01", "Source, medium, capturer, time, capture metadata."), ("EVD-DCM-04", "Classification record", "Control evidence", "TR-REC-02", "Record class, retention category, security classification, access level, tags."), ("EVD-DCM-05", "Publication record", "Control evidence", "TR-REC-03", "Published version, audience, channel, usage metric."), ("EVD-DCM-06", "Record declaration and retention status", "Assurance evidence", "TR-REC-05", "Declaration, retention start and end, audit trail, compliance audit metric."), ("EVD-DCM-07", "Retention expiry record", "Control evidence", "TR-REC-09", "Expiry date, disposition rule, hold check result."), ("EVD-DCM-08", "Disposition certificate and audit log", "Control evidence", "TR-REC-11", "Disposition method, authority, date; the audit log retained."), ("EVD-DCM-09", "Preservation notice and acknowledgements", "Assurance evidence", "TR-HLD-02", "Matter, scope, custodians, acknowledgements, e-discovery KPI."), ("EVD-DCM-10", "Hold release record", "Decision evidence", "TR-HLD-06", "Release decision, authority, date; production record where discovery ran."), ("EVD-DCM-11", "Discard record", "Control evidence", "TR-REC-13", "Content discarded, handling policy rule, hold check result, authority, date; the audit log retained."),
]
EXC = [("EXC-DCM-01", "Provisional Publication", "TR-AV-01", "Release of captured content to a named audience before its classification is complete.", "DR-DCM-05", "Content captured into the repository, provisional access level applied by the data steward, audience named, classification scheduled with a date, Data Security informed, audit log kept; expires at the scheduled classification date.", "Draft / Approved / Expired / Closed")]

SPEC = {
    "meta": {"modelId": "KA-DCM", "name": "Document and Content Management FTS", "knowledgeArea": "Document and Content Management", "version": "0.1", "subjectType": KA_SUBJECT,
             "regionModel": "One FTS per managed element: the Content and Records Management Strategy (scope level), the Information Architecture and Content Repository (scope level), a Record or Content Item of a Data Asset (one per item) and a Legal Hold or e-Discovery Matter (one per matter) run concurrently and are coupled by cross-region constraints, facts and events, never a single subject.",
             "source": SRC_DECK + "; " + SRC_HOWARD + "; " + SRC_PROTOCOL,
             "note": "Four state regions, each its own FTS over one managed element of the Knowledge Area: the Content and Records Management Strategy, the Information Architecture and Content Repository, a Record or Content Item of a Data Asset and a Legal Hold or e-Discovery Matter. The KA never becomes a region of the Data Asset; the item and the hold reach the Global protocol through contributions (destruction only after retention expiry with no active hold, preservation with a retention category assigned, release of published content or a declared record, the hold as the assurance trigger and records retention as the assurance service), all Conditional so assets with no content item are unaffected, and couple to DG, Data Security, Metadata, DSO, Data Architecture and DII.",
             "definition": CONTEXT["definition"], "factBindings": FACT_BINDINGS},
    "context": CONTEXT, "regions": REGIONS, "states": STATES, "transitions": TRANS, "events": EVENTS, "decisionRights": DR, "roles": ROLES, "artefacts": ARTEFACTS, "activities": ACTS, "services": SERVICES, "contributions": CONTRIB, "kaCouplings": KA_COUPLINGS, "crossRegionConstraints": XRG, "stateVectors": VECTORS, "evidence": EVIDENCE, "exceptions": EXC,
    "sources": [
        {"id": "SRC-DCM-001", "source": SRC_DECK, "type": "Primary (image pages, captured)", "location": "Chat upload; OneDrive Data Lifecycle folder", "use": "Definition, goals, drivers, inputs, processes, deliverables, role players, techniques, tools, metrics", "limitations": "The context diagram lists five activities and five deliverables but no item or hold lifecycle; the Record or Content Item states are drafted from Capture and Manage, Retain, Dispose and Archive, and Publish and Deliver Content with the Managed record and Audit trail deliverables; the hold states are drafted from the e-discovery approach, the litigation driver and the E-discovery KPI. Activity 2 carries no phase tag on the diagram; (P) is inferred."},
        {"id": "SRC-DCM-002", "source": SRC_HOWARD, "type": "Design direction", "location": "Chat", "use": "Managed elements (four), Global gating, one record lifecycle with declaration as a state", "limitations": ""},
        {"id": "SRC-DCM-003", "source": SRC_PROTOCOL, "type": "Alignment target", "location": "Private repo models/", "use": "Global transition IDs for contributions; KA transition IDs for couplings", "limitations": ""},
    ],
    "qaNotes": [
        {"severity": "note", "rule": "GA-005", "element": "KA-DCM", "finding": "The strategy and the information architecture change rarely relative to an item and gate it through XRG-DCM-01..07; the Record or Content Item and the Legal Hold are per instance and are the DCM regions that gate Global destruction, preservation and release."},
        {"severity": "note", "rule": "capture", "element": "REG-DCM-REC", "finding": "Item states (captured, classified, published, declared record, archived, retention expired, disposed) and hold states (identified, active, in discovery, released) are drafted from the activities, deliverables and drivers; the context diagram gives no lifecycle. For Howard's review."},
        {"severity": "note", "rule": "scope", "element": "CON-DCM-01", "finding": "All DCM contributions are Conditional and pass when the asset has no record or content item, so structured assets are unaffected; the hold guard on destruction complements the Global XRG-001 hold_active fact rather than replacing it."},
        {"severity": "note", "rule": "phase", "element": "process:2", "finding": "Create Content Handling Policies carries no phase tag on the diagram; (P) inferred and marked so."},
        {"severity": "note", "rule": "derived", "element": "STATES", "finding": "All state names, events, decision rights, holders and services are first-pass drafts from the context diagram; every one is for Howard's review."},
    ],
}

if __name__ == "__main__":
    from ka_build import run_spec
    run_spec(SPEC, "document_content_management.fts.json")
